### ISSUE TITLE
tests/empty_match.t: last test fails due to file ordering issues

### ISSUE THREAD

**Issue by radhermit** [ggreer/the_silver_searcher#1029]
The empty.txt and nonempty.txt files can be returned in either order causing the test to fail some of the time. Sorting the output in some fashion is probably required, but a simple use of sort can't be used due to the stats also being included in the output.

**Comment by aswild** [comment]
I ran into this today as well - `ag_scandir` calls `readdir`, and the `readdir(3)` man page states

>The order in which filenames are read by successive calls to readdir() depends on the filesystem implementation; **it is unlikely that  the  names will be sorted in any fashion.**

empty_match.t passes on an Ubuntu 16.04 system on an ext4 filesystem, but often fails on Ubuntu 16.10 and xfs.  Clearly we can't rely on the ordering of the file list.

I think to fix this we want to collect the output of `ag` into a temporary file, allowing so generate the expected output in 2 steps.
