### ISSUE TITLE
Try to use mmap in a smarter way

### ISSUE THREAD

**Issue by Glandos** [ggreer/the_silver_searcher#1045]
According to http://blog.burntsushi.net/ripgrep/ (which is a very interesting post), mmap calls are really expensive for a lot of file, e.g. a source tree. Simply opening files and try to read them with buffer is faster.
I don't know if reverting an old pull request is as simple as that…

**Comment by ggreer** [comment]
That post is out of date. Ag only uses mmap() on platforms where it's faster (linux, not macos).

**Comment by Glandos** [comment]
OK, sorry for the disturbance then :)
