### ISSUE TITLE
add yarn.lock to default ignore?

### ISSUE THREAD

**Issue by steveinatorx** [ggreer/the_silver_searcher#1054]
yarn is getting more popular as a package manager.  Might be a good idea to add the yarn.lock file to default ignore. 

thanks for the incredible tool!

**Comment by krigstask** [comment]
What's "default ignore"?  I don't think there is one *at all*.

Also, personally I've never heard of *yarn*, but you can always add its files (just like any other) to `~/.agignore`.

**Comment by steveinatorx** [comment]
well there must be a default ignore configuration because ag does not search in node_modules for instance. this can be closed

**Comment by krigstask** [comment]
@steveinatorx 
> there must be a default ignore configuration because ag does not search in node_modules for instance

But it does.  You probably have `node_modules` *gitignored* or something.

**Comment by steveinatorx** [comment]
aaaa https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage
ok - i should RTFM.
