### ISSUE TITLE
Ag failing to find files after 2 recursion levels

### ISSUE THREAD

**Issue by joaqo** [ggreer/the_silver_searcher#1066]
Hi, I am currently running a search in the following directory structure:

```
   root 
     |--> subfolder1
     |        |--> subsubfolder2
     |                     |--> .env
     |--> file1.env
     |--> file2.env
```

If I run `ag --hidden -g ".env"` on the root folder, ag only returns `file1.env` and `file2.env`. It fails to find the nested file `.env`.

If I run the same serach while inside the folder named `subfolder` ag finds the `.env` file just fine.

This seems really strange.

**Comment by knjmooney** [comment]
This works fine for me
```
caoimhin@craic:/tmp/root
 -> tree -a
.
├── file1.env
├── file2.env
└── subfolder1
    └── subfolder2
        └── .env

2 directories, 3 files
caoimhin@craic:/tmp/root
 -> ag --hidden -g ".env"
file1.env
file2.env
subfolder1/subfolder2/.env
```
Are you using version control? Could the subfolder be hidden by some "ignore" file?

**Comment by joaqo** [comment]
@knjmooney Hey thanks, you were right, it was version control related. When I went into the subfolder, ag stopped reading my .gitignore file, and thus didnt ignore my .env files. Using a -U flag fixed it.

Thanks a lot!

**Comment by jschpp** [comment]
How about closing this then? :)

**Comment by nelsonauner** [comment]
@joaqo  bump to close this issue! :)

**Comment by joaqo** [comment]
Sorry! Closing...
