### ISSUE TITLE
exit code

### ISSUE THREAD

**Issue by ghazel** [ggreer/the_silver_searcher#1070]
Feature request for exit code that indicates if a match occurred (0 for match, 1 for no match, >=2 for error)

like with grep (https://www.gnu.org/software/grep/manual/html_node/Exit-Status.html):
```bash
$ echo foo | grep foo ; echo $?
foo
0
$ echo foo | grep bar ; echo $?
1
$ grep foo not_real ; echo $?
grep: not_real: No such file or directory
2
```

current `ag` behavior:
```bash
$ ag --version
ag version 0.19.2
$ echo foo | ag foo ; echo $?
foo
0
$ echo foo | ag bar ; echo $?
0
$ ag foo not_real ; echo $?
ERR: Error stat()ing: not_real
ERR: Error opening directory not_real: No such file or directory
0
```

**Comment by aswild** [comment]
Not really an issue in the latest `ag` (version 0.19.2 is 3 years old). It does however return 1 on "file not found" rather than 2.

```
$ ./ag --version
ag version 1.0.2

Features:
  +jit +lzma +zlib
$ echo foo | ./ag bar ; echo $?
1
$ ./ag foo not_real ; echo $?
ERR: Error stat()ing: not_real
ERR: Error opening directory not_real: No such file or directory
1

```

**Comment by ggreer** [comment]
In the latest version of ag the exit code is 0 if match found, 1 if no match found, and 2 if a fatal error occurred (`die()` is called). Right now, a nonexistent file isn't considered a fatal error (even if it's the only file ag tries to search).

**Comment by ghazel** [comment]
Great! Sorry for the old version; it was the latest in "apt". Ubuntu doesn't like up to date software.
