### ISSUE TITLE
Ag thinks xlsx is a zip file

### ISSUE THREAD

**Issue by CeleritasCelery** [ggreer/the_silver_searcher#1078]
when searching through a directory with [xlsx](http://www.openwith.org/file-extensions/xlsx/883) files (Excel XML) Ag gives the error 
```
ERR: Cannot decompress zipped file <file.xlsx>
ERR: Zip files not yet supported: <file.xlsx>
```
even though these files are uncompressed plain-text and perfectly searchable. Is there an easy way to tell Ag that these are not compressed files or will a fix need to be made?

**Comment by andreasstieger** [comment]
Are you sure?

```
unzip -t test1.xlsx 
Archive:  test1.xlsx
    testing: _rels/.rels              OK
    testing: docProps/app.xml         OK
    testing: docProps/core.xml        OK
    testing: xl/_rels/workbook.xml.rels   OK
    testing: xl/sharedStrings.xml     OK
    testing: xl/worksheets/sheet1.xml   OK
    testing: xl/styles.xml            OK
    testing: xl/workbook.xml          OK
    testing: [Content_Types].xml      OK
No errors detected in compressed data of test1.xlsx
```

**Comment by CeleritasCelery** [comment]
@andreasstieger You are correct. I was examining it with less which auto unzips. Any idea when xlsx files will be supported?
