### ISSUE TITLE
Add option to not descend directories on other filesystems

### ISSUE THREAD

**Issue by stweller** [ggreer/the_silver_searcher#1082]
In my environment, there are symlinks to directories that are actually mounted via NFS. It would be nice to have an option to not search such directories, as these just cannot be searched as fast as locally mounted ones. This would correspond to the `-xdev` option of `find` (and it only makes sense in combination with `-f`).

**Comment by ggreer** [comment]
Did you try `--one-device`?

**Comment by stweller** [comment]
Sorry for my stupidity, that is obviously what I was looking for. Thanks!
