### ISSUE TITLE
sh: 1: git: not found

### ISSUE THREAD

**Issue by AnrDaemon** [ggreer/the_silver_searcher#1088]
Constantly getting "sh: 1: git: not found" messages on every ag invocation.
And yes, there's no git on the system. Not even svn. Or any other VCS. It's a development constainer only accessed via network share and SSH.

**Comment by ggreer** [comment]
What platform are you on? What version of ag are you using? How are you invoking ag?

**Comment by AnrDaemon** [comment]
Ummm, my bad. Just noticed the version is not what I'm used to. I should upgrade.
Will reopen if confirmed after that.

**Comment by AnrDaemon** [comment]
Git it all right after building a new deb.
And the build itself went rather smooth, thank you!
