### ISSUE TITLE
Disabling all ignoring

### ISSUE THREAD

**Issue by superDuperCyberTechno** [ggreer/the_silver_searcher#1105]
According to the [docs](https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage) ag respects .gitignore, I do not want that.

In fact, I'd prefer it if ag didn't ignore a single file, regardless of convention.

How do I achieve this?

**Comment by canvural** [comment]
You can try `-u --unrestricted` flag.

**Comment by superDuperCyberTechno** [comment]
Thanks a lot. Don't know how many times I tried googling for it or scrutinized the man page. This was my last resort. Much appreciated.

**Comment by canvural** [comment]
It was in the man page.

**Comment by qeatzy** [comment]
another useful related option is `-t` or `--all-text`
below excerpted from output of `ag -h`
```
-t --all-text           Search all text files (doesn't include hidden files)
-u --unrestricted       Search all files (ignore .ignore, .gitignore, etc.;
                          searches binary and hidden files as well)

```
