### ISSUE TITLE
how create a preference file?

### ISSUE THREAD

**Issue by slimane** [ggreer/the_silver_searcher#111]
one question, how create a .ackrc style preference file?

**Comment by trinitronx** [comment]
:+1: for this feature...  People coming from `ack` seem to expect a portable way to use their `.ackrc` with `ag`, or at least modify & adapt their existing one for use with `ag`.  Aliases are ok for setting default arguments like `alias ag='ag --pager="less -SMFRX"'`, but things can get unwieldy pretty quick if you have a lot of arguments you want to add.  I can see that implementing this in a way that has to parse the file would be not very fast and would make it harder to maintain.

Perhaps the implementation could be quick and dirty:   simply check for an `~/.agrc` file, then if it exists read it and append the lines found to the `argv` array, then continue as normal.   This would let `parse_options(argc, argv, &base_paths, &paths);` do all the hard work, makes it easier to maintain and allows for future-proof support for other options added later.  If the `~/.agrc` file doesn't exist, then skip the whole code branch to read it in for speed.

**Comment by diego898** [comment]
I'd just like to say this would be very useful for me. Its a shame that the only way to do this is with aliases.
