### ISSUE TITLE
[Question] How to simulate grep square brackets

### ISSUE THREAD

**Issue by pachonk** [ggreer/the_silver_searcher#1115]
In ps, I use `ps ax | grep [t]mux` to filter out the current running grep. Is there a way to do this with ag?

**Comment by aswild** [comment]
Have you tried using it exactly like grep?

```
% ps ax | grep '[t]mux'
  942 pts/1    Ss+    0:00 tmux
  946 ?        Ss     0:03 tmux

% ps ax | ag '[t]mux'
  942 pts/1    Ss+    0:00 tmux
  946 ?        Ss     0:03 tmux
```

**Comment by pachonk** [comment]
I could swear I didn't need quotes on grep. Blah. Sorry.

**Comment by aswild** [comment]
Whether or not you need quotes depends on your shell, not the program you're running with it.

In addition to being regex syntax. square brackets are shell glob patterns so if a file named `tmux` existed in your PWD, the shell would "expand" the glob to match the file. If there's no match, the brackets will probably get passed on to the args of the command you're running.

When in doubt, it's better to quote things which your shell might mangle so you know what's getting passed to the program.

**Comment by pachonk** [comment]
Thanks for the tips! I could SWEAR it worked, but even when I try real grep (I aliased it because grep is my muscle memory :p), it doesn't work how I thought it did.
