### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by jinxmcg** [ggreer/the_silver_searcher#1132]
Hi, 
I get segfault when searching this:

```
#ag '(?=(?:.|\n)*?first)(?:.|\n)*?second' access.log
Segmentation fault (core dumped)
```

```
#ag --version
ag version 0.31.0
```

Maybe my regex is wrong but should not give segfault, right?

Thanks for making such a great piece of code.

:)

**Comment by canvural** [comment]
Is upgrade an option for you? It works fine with version 2.0

**Comment by jinxmcg** [comment]
Yes it is.
