### ISSUE TITLE
Is there a way to index the directory?

### ISSUE THREAD

**Issue by nmklong** [ggreer/the_silver_searcher#1154]
Is there any way to index the directory to help searching faster?

**Comment by aswild** [comment]
Just let the operating system handle it transparently. After searching the first time, all the files will be cached in RAM (assuming there's enough unused memory on your system) and subsequent searches are significantly faster.

Searching the linux kernel tree (733 MB in 60,314 files) drops from 47 sec to 0.7 sec the second time around.
