### ISSUE TITLE
ag -z does not work on directories

### ISSUE THREAD

**Issue by ylluminarious** [ggreer/the_silver_searcher#1183]
For some reason, running `ag -z` on a directory does not work for me anymore, although it used to. What I mean is that running this will work:

```sh
$ ag -z -- my_string my_file.gz

100:here is my_string
```

Whereas running this will not work:

```sh
$ ag -z -- my_string /path/to/dir_containing_my_file
$ echo $?
1
```

I know that this behavior *used to* work, but it does not anymore. Why could that be and how do I get this behavior back?

**Comment by ylluminarious** [comment]
@ggreer FYI, I have confirmed that the last version which had this behavior was `1.0.2`. So I guess this feature disappeared quite a while back.

**Comment by ylluminarious** [comment]
@ggreer Any thoughts on this issue? No rush, just wondering.

**Comment by aswild** [comment]
It's working for me in the latest upstream, v2.1.0, and my personal fork.

My guess is you have an ignore file somewhere which is causing ag to skip my_file.gz on your setup. Run it with `-D` and it should say what's getting skipped.

**Comment by ylluminarious** [comment]
@aswild Thank you very much for that suggestion! You were right on the money; the problem was a line containing `*.gz` in my `~/.gitignore_global `. Is there a way for me to tell `ag` to not use certain things in my `git` ignore files? That would be ideal in this situation.
