### ISSUE TITLE
silver searcher how to unignore files in the .gitignore

### ISSUE THREAD

**Issue by ohadperry** [ggreer/the_silver_searcher#1189]
I have a folder of aliases. these are bash files. 
some are sensitive, so I keep them in a `.gitignore`

    ~/.bash_utilities
       bash_a.sh
       bash_b.sh
       .gitignore

.gitignore:
bash_b.sh  

the problem is that my `silver searcher` looks at the `.gitignore` and skips those files when looking. 

how do I tell the `silver searcher` to ignore the `.gitignore` and look in all the files in the directory.

my current command is 

    ag $1 ~/.bash*

**Comment by ohadperry** [comment]
nvm mind, 
got the answer 
```
-u --unrestricted

Search all files. This ignores .ignore, .gitignore, etc. It searches binary and hidden files as well.

-U --skip-vcs-ignores

Ignore VCS ignore files (.gitignore, .hgignore), but still use .ignore.
```

**Comment by benlieb** [comment]
An option like `--noignore-dir` would be very helpful for me. 99% of what is in my .gitignore I want to be ignored, but some I don't. Am I supposed to keep a version of .ignore that is just like my .gitignore, except these bits?
