### ISSUE TITLE
.gitignore not detected if run inside a sub-project and .gitignore is in parent folder

### ISSUE THREAD

**Issue by greduan** [ggreer/the_silver_searcher#1193]
The folder structure is as follows:

```
- .git
- .gitignore
- package.json
- packages/
  - a
    - node_modules/
    - package.json
```

There is no `.gitignore` present in the sub-folder. Content of `.gitignore` includes the following:

```
node_modules/
```

If I'm in root folder and run `ag -g ''`, it returns a list of files, without the `node_modules` folder's content, as expected.

If I'm in the sub-project and run `ag -g ''`, it  returns a list of files, also including the contents of the `node_modules` folder. This is unexpected behaviour.

I include the `package.json` files and `.git` files since I'm not sure, but `ag` may be using them to figure out where to look for a `.gitignore`, and it stops at the folder it finds the first `package.json` or something.

Thanks for your help. 🙂

**Comment by rr-** [comment]
Duplicate of #1031

**Comment by greduan** [comment]
I will close. BTW if you follow the thread of duplicates, it ends up at https://github.com/ggreer/the_silver_searcher/issues/144.
