### ISSUE TITLE
Limit line length of results

### ISSUE THREAD

**Issue by tgice** [ggreer/the_silver_searcher#1240]
I occasionally run into this annoyance when using ag to search my tree of code:

I'll get a match on a file that has really long lines in it, like some markup (XML or something such), and it's in a list of other results, but this causes the screen to scroll for a ton of lines and really limit the usefulness in that context.

Of course I could pipe the output to '| cut -c1-80' or something like that, and I've done that, but then I lose my pretty colors / highlighting that ag does (which I love).

So, my suggestion would be an off-by-default option that lets the user say "chop off all results to no more than this many characters".

I guess even more ideally (more difficult to add I'm sure) would be something that would take that character limit of 80, and make sure that instead of just blindly chopping off each result line, ag makes sure to include the first match on that line in the output, but still not exceed the limit.

E.g., if I was searching for 'a' in this line, with a limit of 5:
__-------------------------a-------------
instead of getting
__---
I'd get something like:
a----
or
----a

Not sure how useful this would be for anyone else.  I guess if there's some pre-existing 'cut' utility that would run on Windows and not quash the nice color output on the console, that'd work just as well for me.

Thanks for any effort expended on this one.

**Comment by tgice** [comment]
Ah, I now see the '--only-matching' option, which in a way does solve my issue.

I guess it might be nice still to have some form of what I'd suggested though (especially the second, more complex suggestion) for giving a bit more context around the search term.

**Comment by dylan-chong** [comment]
Try `ag -W 10 'hello'`.

I don't know why this isn't in the documentation

**Comment by tgice** [comment]
Thanks Dylan, I'm surprised I missed that one.

I was probably searching the usage for 'cut' and not truncate.  This works about 99% of what I want, so I'm happy.

**Comment by h43z** [comment]
-W here is not the solution to the problem.

```code
% echo "-----------a--------" | ag -W 5 a
----- [...] # a missing from result
```

I'm personally looking for something that @tgice asked for? Is there anything like that in ag?

**Comment by AtomicNess123** [comment]
I'm also interested in displaying only a certain line length, as I search text and long paragraphs tend to make things less readable.

**Comment by k00ka** [comment]
Something like _show max this many characters around the match_ would be nice. Another option would be to hide output longer than a certain length, like _grep_ or _diff_ do with binary files.

**Comment by iburunat** [comment]
I second the proposal!
