### ISSUE TITLE
-cpp seems to set -c

### ISSUE THREAD

**Issue by GavinHigham** [ggreer/the_silver_searcher#1246]
If I try to use ag to search a collection of .cpp files for matches, using a command like

`ag -cpp SomeQuery`

I only get the list of files containing a match, and a count (as if using the option -c) instead of the actual matching lines I expect.

**Comment by shabbyrobe** [comment]
Is that exactly as you typed it? If so, you are missing a dash. It should be `ag --cpp SomeQuery`.

Without the second dash, it is interpreted as `ag -c -p -p`.

**Comment by GavinHigham** [comment]
Ah, I think you are right. Maybe a slight tweak to the -h text could save some future user my embarassement.
