### ISSUE TITLE
how can i search for only unicode characters?

### ISSUE THREAD

**Issue by foresightyj** [ggreer/the_silver_searcher#1248]
The initial attempt is `ag '[\u4e00-\u9fa5]+'` which is unicode of Chinese characters. 

```
➜  FHT.Web git:(master) ✗ ag '[\u4e00-\u9fa5]+'                
ERR: Bad regex! pcre_compile() failed at position 2: PCRE does not support \L, \l, \N{name}, \U, or \u
If you meant to search for a literal string, run ag with -Q
```

After 20 minutes searching for PCRE standard about unicode, I tried the following and none of them work:

```
➜  FHT.Web git:(master) ✗ agweb '\p{Han}'                     
➜  FHT.Web git:(master) ✗ agweb '\p{InCJK_Unified_Ideographs}'
ERR: Bad regex! pcre_compile() failed at position 27: unknown property name after \P or \p
If you meant to search for a literal string, run ag with -Q

```

**Comment by JFLarvoire** [comment]
PCRE1 does not support \uXXXX escape sequences. This would be one of the advantages of switching to PCRE2 in ag.
Anyway, you can search for non-ASCII characters this way in the current version:
ag '[^\x00-\x7F]'

**Comment by foresightyj** [comment]
Thanks a lot for the answer. Non-ASCII works well for my case.
