### ISSUE TITLE
No support for printing selected capture groups

### ISSUE THREAD

**Issue by ju1ius** [ggreer/the_silver_searcher#1252]
Hi,
First thank you very much for this wonderful tool, which I use almost every day.

The only thing I miss however is the possibility to print only selected capture groups, like with [pcregrep](https://www.pcre.org/original/doc/html/pcregrep.html).
From `man pcregrep`:
> <b>-o</b><i>number</i>, <b>--only-matching</b>=<i>number</i>
    Show  only  the  part  of the line that matched the capturing parentheses of the given number. Up to 32 capturing parentheses are supported, and <b>-o0</b> is equivalent to <b>-o</b> without a number. Because these options can be given without an argument (see above), if an argument is present, it must be given in the same shell item,  for  example, <b>-o3</b>  or <b>--only-matching=2</b>.  The comments given for the non-argument case above also apply to this case. If the specified capturing parentheses do not exist in the pattern, or were not set in the match, nothing is output unless the file name or line number are being printed.

Thanks for taking the time to read this report.
I hope you'll consider adding this feature.

**Comment by detj** [comment]
ag has an `-o/--only-matching` flag, but the contextual meaning is different.

```
-o --only-matching
              Print only the matching part of the lines.
```

It does _*not*_ show the results of the capture groups. It would be nice to have an additional flag that outputs captured groups.

_using ag 2.1.0_

**Comment by ju1ius** [comment]
Yep, `pcregrep` has that too.
A raw `-o` is functionally the same as `-o0`, it shows only capture group `0`.

**Comment by dmnd** [comment]
A workaround for outputting only a captured group is described here: https://github.com/ggreer/the_silver_searcher/issues/400#issuecomment-418454903

**Comment by genivia-inc** [comment]
I would suggest to perhaps add a new option to produce formatted output. For example `--format="%1\n"` outputs capture group 1 only. [Ugrep implements this as an option](https://github.com/Genivia/ugrep#replace) when used with option `-P` (Perl matching).

This offers the most flexible way to use group captures, including multiple e.g. `--format="%1 %2\n"` to output groups 1 and 2.

There are also two problems to support an optional value with `-o`. First, it is not compatible with most other grep tools. Second, this causes ambiguity when combining options `-o` and `-0` together, giving `-o0` that has two meanings: either `-o` with value 0 or `-o -0`. Granted, `-o0` is the default `-o` value, but still.

**Comment by Aex12** [comment]
This is the only thing I'm missing from ack, which already includes it as the --output option.

`--output=expr
  Output the evaluation of expr for each line (turns off text highlighting). If PATTERN matches more than once then a line is output for each non-overlapping match.

  expr may contain the strings "\n", "\r" and "\t", which will be expanded to their corresponding characters line feed, carriage return and tab, respectively.

  expr may also contain the following Perl special variables:

  $1 through $9
    The subpattern from the corresponding set of capturing parentheses. If your pattern is "(.+) and (.+)", and the string is "this and that', then $1is "this" and $2 is "that".

  $_  The contents of the line in the file.

  $.  The number of the line in the file.

  $&, "$`" and "$'"
    $& is the the string matched by the pattern, "$`" is what precedes the match, and "$'" is what follows it. If the pattern is "gra(ph|nd)" and the string is "lexicographic", then $& is "graph", "$`" is "lexico" and "$'" is "ic". Use of these variables in your output will slow down the pattern matching.

  $+  The match made by the last parentheses that matched in the pattern. For example, if your pattern is "Version: (.+)|Revision: (.+)", then $+ will contain whichever set of parentheses matched.

  $f  $f is available, in "--output" only, to insert the filename. This is a stand-in for the discovered $filename usage in old "ack2 --output", which is disallowed with "ack3" improved security.

     The intended usage is to provide the grep or compile-error syntax needed for editor/IDE go-to-line integration, e.g. "--output=$f:$.:$_" or "--output=$f\t$.\t$&"`

**Comment by ju1ius** [comment]
For what it's worth, this is how it can be achieved with `ripgrep`:
```sh
rg 'id="([^"]+)"' --only-matching --replace '$1'
```

**Comment by ju1ius** [comment]
Closing as not planned since the project seems finished and I'm not using it anymore.
