### ISSUE TITLE
-Q string literal doesn't work with backslash?

### ISSUE THREAD

**Issue by ryanmortier** [ggreer/the_silver_searcher#1276]
Command I'm using:

```ag -Q App\User```

I would expect the string literal `App\User` to be searched for but it appears that I still need to escape the backslash.

The command that does work is:

``` ag -Q App\\User```

Is this intended behaviour or a bug?

**Comment by aswild** [comment]
This is a shell quoting/escaping issue, nothing to do with ag. Your shell turns `\U` into just `U`. Backslashes and other special characters need to be quoted or escaped for any shell command.

**Comment by ryanmortier** [comment]
Thanks for clarifying.
