### ISSUE TITLE
POTENTIAL CONTRIBUTORS BEWARE :: This project does not accept pull requests

### ISSUE THREAD

**Issue by mingwandroid** [ggreer/the_silver_searcher#1284]
Please see [this thread](https://news.ycombinator.com/item?id=18516782):

The README.md should make it clear that the maintainer has zero interest in accepting or reviewing pull requests. In the long term, the project should probably be forked (or forgotten about, there are more open-source friendly options out there, like ripgrep, and for some, contributing to that would involve learning rust, which some may like to do).

**Comment by ggreer** [comment]
Please stop.
