### ISSUE TITLE
Why is AG_ZIP "Unsupported compression type" ? 

### ISSUE THREAD

**Issue by ampresent** [ggreer/the_silver_searcher#1294]
I get this error when I'm trying to search a .zip file
`ERR: Unsupported compression type: 3`

https://github.com/ggreer/the_silver_searcher/blob/1b06a9fd8d9ad0aaf235b4a752e605dfd4bb7ced/src/zfile.c#L87-L119

**Comment by genivia-inc** [comment]
I'm surprised that type 3 is still used? Please note that *"Methods 1-6 are legacy algorithms and are no longer recommended for use when compressing files."* See the latest zip [APPNOTE 6.3.6](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT).

Given this, it seems unnecessary to support compression type 3.

For a wide range of use cases, compression types 0 (stored), 8 (deflate), 14 (LZMA). Perhaps also types 9 (enhanced deflate) and 95 (XZ). See also [wikipedia ZIP compression](http://fileformats.archiveteam.org/wiki/ZIP).  Note that type 0 is often used to store empty and small files and should not be flagged as an error by ag either.

I should add that [ugrep supports compression types 0, 8, 14, and 95](https://github.com/Genivia/ugrep#archives).

**Comment by ampresent** [comment]
Thanks
