### ISSUE TITLE
output get trailing ^M at the end of line 

### ISSUE THREAD

**Issue by yuiwong** [ggreer/the_silver_searcher#1304]
Hey guys, I've been using ag for a while. It works like a charm. But there is a small issue gets me all the time. I tried looking for answers but it seems like I'm the only one who encounter this problem.
ag will output a trialling ^M at the end of each line.

In vim it looks like this:
![1](https://user-images.githubusercontent.com/10131032/52696960-53999d00-2fab-11e9-8af6-30535898e93c.PNG)

Notepad will treat the extra ^M as newline.
![image](https://user-images.githubusercontent.com/10131032/52696895-28af4900-2fab-11e9-9a0f-b8e446c00446.png)

I don't know which program cause this, but I think it must be one of the followings:  ag, cmder, vim.
I did some test, it seems like ag or cmder is outputing the extra ^M
Maybe I'm not setting things correctly?

Here are my test spec.  
```
Command Used:
    ag --vimgrep --fixed-strings -- "->renderGroup" >> test.txt
ag version:
    2.20 unofficial build
VimSettings:
    set fileformats=dos,unix
    set grepprg=ag\ --vimgrep
    set grepformat=%f:%l:%c:%m
OS:
    windows 10 64bit
```

**Comment by EclipseLiao** [comment]
Hi, 

I have the same issue, too.
I use cmd.exe to get ag's output like:

ag scan .   > t
======================
And I found every endofline have 
**0d0d0a**

**Comment by JFLarvoire** [comment]
Hi,
Try using this build of ag for Windows, which I think does not have this problem:
https://github.com/JFLarvoire/the_silver_searcher/releases

**Comment by yuiwong** [comment]
Thank you, @JFLarvoire   
I think your build solve the issue.
