### ISSUE TITLE
silversearcher-ag vs silversearcher-ag-el 

### ISSUE THREAD

**Issue by kkhan01** [ggreer/the_silver_searcher#1315]
This is more of a question than issue. As the title may suggest, I'm unsure of the difference between the packages silversearcher-ag and silversearcher-ag-el  for debian.

**Comment by cbandy** [comment]
```
$ apt-cache show silversearcher-ag
...
Homepage: https://github.com/ggreer/the_silver_searcher
...
```

```
$ apt-cache show silversearcher-ag-el
...
 ag.el is simple ag frontend for Emacs, loosely based on ack-and-half.el.
...
Homepage: https://github.com/Wilfred/ag.el
...
```

**Comment by kkhan01** [comment]
I'm still fairly unsure. I figured the el had something to do with emacs based off of elisp, but as evident by [this link](https://agel.readthedocs.io/en/latest/installation.html) one should install the ggreer binary and use the melpa package. What purpose does silversearcher-ag-el serve?

**Comment by kkhan01** [comment]
I shall ask in Wilfred repo instead. It seems more relevant, thanks for everything.
