### ISSUE TITLE
为啥不支持中文

### ISSUE THREAD

**Issue by StephenWu5** [ggreer/the_silver_searcher#1322]
![image](https://user-images.githubusercontent.com/32475322/58301457-18640100-7e19-11e9-9646-50c1c091ea22.png)

**Comment by cyberrob** [comment]
Did you misspell this cmd? It shows `Ag` in your screenshot.

**Comment by cmonkey** [comment]
![image](https://user-images.githubusercontent.com/664050/59499516-2104a000-8eca-11e9-96fe-c9d0017dab4b.png)
可以支持呀

**Comment by StephenWu5** [comment]
好的，谢谢了

**Comment by kingreatwill** [comment]
我的也不支持中文

**Comment by StephenWu5** [comment]
已解决
