### ISSUE TITLE
How to use it in a qt project? 

### ISSUE THREAD

**Issue by LinArcX** [ggreer/the_silver_searcher#1323]
Hi. I'm developing a qt application. Currently I'm using Qprocess to use ag. But I want to use it directly in my code. But I don't know how. Is there any sample to follow?

**Comment by gloaming** [comment]
Are you trying to ask whether you can use `ag` as a _library_? AFAIK it does not provide any API.

**Comment by LinArcX** [comment]
Yes. Api usage. So I close this issue..
