### ISSUE TITLE
Error in documentation for -c --count parameters

### ISSUE THREAD

**Issue by boared** [ggreer/the_silver_searcher#1336]
This part of the documentation seems wrong.

```
-c --count: Only print the number of matches in each file. Note: This is the number of matches, not the number of matching lines. Pipe output to wc -l if you want the number of matching lines.
```

I think the fix should be `s/matching lines/matching files`

Test file:

```
cat cat cat
dog
dog dog
bull
bull
bull
```

Test output:

```
$ ag -c cat
test:3
```

```
$ ag -c dog
test:3
```

```
$ ag -c bull
test:3
```

**Comment by vinaygudarad** [comment]
I dont understand whats the issue correctly. If u explain it I would like to work on this

**Comment by theinfinitywritings** [comment]
Can you please specify what is your desired output for the test file

**Comment by boared** [comment]
Sorry to drop the ball here. I believe that help message has changed since I filed this issue so I'm going to close it. But before that, just to explain the problem better, this part `Pipe output to wc -l if you want the number of matching lines` will actually show the number of matching files, not matching lines.
