### ISSUE TITLE
no rpm available in centos8

### ISSUE THREAD

**Issue by ssbarnea** [ggreer/the_silver_searcher#1343]
Apparently there is no rpm available in centos8, even after enabling epel8.

This makes the documentation misleading.

**Comment by snlnspc** [comment]
I'm missing this a lot too!

**Comment by carlwgeorge** [comment]
Bugs for EPEL packages (including requests to build for a new branch) should be reported on [Red Hat Bugzilla](https://bugzilla.redhat.com), as described [here](https://fedoraproject.org/wiki/EPEL#Communicating_with_the_EPEL_SIG).  EPEL 8 was requested in [rhbz#1753978](https://bugzilla.redhat.com/show_bug.cgi?id=1753978) and resolved about a month ago.

**Comment by ssbarnea** [comment]
I am going to close this since I switched to [ripgrep](https://github.com/BurntSushi/ripgrep) (rg) which is available on all platforms using their package managers.
