### ISSUE TITLE
Searching in current directory does not work

### ISSUE THREAD

**Issue by alexreg** [ggreer/the_silver_searcher#1360]
If you search in the current directory (i.e., `ag pattern` or `ag pattern .`), then no results are found, and `ag` exits immediately. If however you specify any subdirectory, it finds results as it should. This is surely not intended behaviour.

**Comment by fairiestoy** [comment]
Was curious on this behaviour, but i could not replicate it. If i call` ag "int main"` or `ag "int main" .` , ag finds results and prints them.

Do you get any output at all?

**Comment by alexreg** [comment]
Nope, no output. It exits immediately with an exit code of 1.

**Comment by JFLarvoire** [comment]
Could it be that you have a .gitconfig or .gitignore file that excludes the files you expect to search in?
Try using `ag -u pattern` to work around that.

**Comment by alexreg** [comment]
@JFLarvoire Thanks, that would make sense! Perhaps by specifying a subdirectory on the command-line, it does not pick up the `.gitconfig` / `.gitignore` file (I forget the specific test case on my computer).
