### ISSUE TITLE
--xml option is available?

### ISSUE THREAD

**Issue by yamatakau08** [ggreer/the_silver_searcher#1361]
```
~/bin/sqlite3_sample` $ ag --version

ag version 2.2.0

Features:
  +jit +lzma +zli`

~/bin/sqlite3_sample $ ag --list-file-types
The following file types are supported:
  ...
  --plone
      .pt  .cpt  .metadata  .cpy  .py  .xml  .zcml
  ...
  --xml
      .xml  .dtd  .xsl  .xslt  .ent  .tld  .plist
  ...
```

grep command puts out the search pattern result.
```
~/bin/sqlite3_sample $ grep heading chap*.xml
chap1-1.xml:    <heading id="0" hj="わーい!" he="Wow!">
...
```

on the other hand, ag doesn't put out results.
```
~/bin/sqlite3_sample $ ag --xml heading
~/bin/sqlite3_sample $
~/bin/sqlite3_sample $ ag -G '\.xml' heading
~/bin/sqlite3_sample $
```

I rename file suffix .xml to .html and specified --html option for ag .
I could get result eventually.

```
~/bin/sqlite3_sample $ cp chap1-1.xml chap1-1.html
~/bin/sqlite3_sample $ ag --html heading
chap1-1.html
3:    <heading id="0" hj="わーい!" he="Wow!">
...
```

I assume --xml option doesn't work.
Could you teach me what is wrong?

**Comment by yamatakau08** [comment]
The environment of the above post is the following.
```
~/b/sqlite3_sample> uname -a
MINGW64_NT-10.0-17763 JPC00183513 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
```

I've executed "ag --xml ... " on Mac. works fine.
So, I assume the cause in environment.

**Comment by JFLarvoire** [comment]
Could it be that you have a .gitconfig or .gitignore file that excludes the xml files you want to search in?
The --xml option (or any other type option) does not override those git exclusions, which is a bug in my opinion.
Try using `ag -u --xml heading` to work around that.

**Comment by yamatakau08** [comment]
> Could it be that you have a .gitconfig or .gitignore file that excludes the xml files you want to search in?

about .gitconfig is configuration file and I assume related with nothing about xml.

about .gitignore

```
~/b/sqlite3_sample> cat     .gitignore | grep -i xml
~/b/sqlite3_sample> cat ~/.gitignore | grep -i xml
```
There is no rule excludes xml in .gitignore.

I wonder why ag doesn't handling `--xml` option on mingw64.

> Try using `ag -u --xml heading` to work around that.

```
~/b/sqlite3_sample> ag -u --xml heading
chap1-1.xml
3:    <heading id="0" hj="わーい!" he="Wow!">
18:    </heading>
20:    <heading id="1" hj="やったー!" he="Yahoo!">
25:    </heading>
27:    <heading id="2" hj="よかった" he="Excellent!">
...
```

anyway, your advice works fine.
Thank you for your advice.

**Comment by yamatakau08** [comment]
> I wonder why ag doesn't handling --xml option on mingw64.

I'm very sorry.
I found  ~/.agignore has *.xml entry.
I remove that, works fin.e
