### ISSUE TITLE
Why does `ag --hidden pattern` not search `.local` dir under current dir?

### ISSUE THREAD

**Issue by oskarkv** [ggreer/the_silver_searcher#1382]
I'm in a directory with a subdirectory called `.local`. If I do `ag --hidden pattern` the `.local` subdirectory is not searched. Why? How can I include it?

**Comment by marc-guenther** [comment]
Works perfectly fine for me:
```
/tmp/foo$ mkdir .local
/tmp/foo$ echo hallo >.local/world.txt
/tmp/foo$ echo hallo >world.txt 
/tmp/foo$ ag hallo
world.txt
1:hallo
/tmp/foo$ ag --hidden hallo
world.txt
1:hallo

.local/world.txt
1:hallo
```

`.local` must be in your `.ignore` file. Try `--unrestricted`.

**Comment by oskarkv** [comment]
Oh, it doesn't search files which are in `.gitignore`.
