### ISSUE TITLE
False positive is_binary even for UTF-8

### ISSUE THREAD

**Issue by gsakkis** [ggreer/the_silver_searcher#1416]
There are already quite a few issues (#1278, #1204, #1085, #818, #466, ...) about failing to search files determined to be binary and requests to add a `--as-text` or `--text` option to bypass the autodetection (#1184, #1311). The common response is that `ag` works only on UTF-8 encoded files. However it seems it can be tricked even by (presumably?) UTF-8:
```
$ cat file.txt 
what is your 𝗔𝗚𝗘?

$ file file.txt 
file.txt: UTF-8 Unicode text

$ grep is file.txt 
what is your 𝗔𝗚𝗘?

$ ag is file.txt 
$ ag --search-binary is file.txt 
Binary file file.txt matches.
```

See attached `file.txt`

[file.txt](https://github.com/ggreer/the_silver_searcher/files/5434564/file.txt)

**Comment by mwgamera** [comment]
The UTF-8 detection is clearly missing the third branch for 4-byte characters U+10000–10FFFF. So it actually ends up supporting CESU-8 instead of UTF-8 and yields 4 suspicious_bytes for every UTF-8-encoded non-BMP character.
https://github.com/ggreer/the_silver_searcher/blob/a61f1780b64266587e7bc30f0f5f71c6cca97c0f/src/util.c#L359-L372

This fixes it (albeit in ugly style):
```diff --git a/src/util.c b/src/util.c
index 90ffb6f..5c30fd9 100644
--- a/src/util.c
+++ b/src/util.c
@@ -368,6 +368,12 @@ int is_binary(const void *buf, const size_t buf_len) {
                     i++;
                     continue;
                 }
+            } else if (buf_c[i] > 239 && buf_c[i] < 248 && i + 3 < total_bytes) {
+                i++;
+                if (buf_c[i] > 127 && buf_c[i] < 192 && buf_c[i + 1] > 127 && buf_c[i + 1] < 192 && buf_c[i + 2] > 127 && buf_c[i + 2] < 192) {
+                    i += 2;
+                    continue;
+                }
             }
             suspicious_bytes++;
             /* Disk IO is so slow that it's worthwhile to do this calculation after every suspicious byte. */
```
