### ISSUE TITLE
List all files

### ISSUE THREAD

**Issue by blueray453** [ggreer/the_silver_searcher#1493]
How can I list all files using ag? I mean, I do not want to use a search term.

I want to do this so that I can find all files except ignored (.gitignore) files.

**Comment by ernstki** [comment]
I think `ag -l` (lower-case ell) does what you want.

A careful review of [the man page](../blob/master/doc/ag.1.md) and a bit of experimentation can often resolve issues like this, though.

![A screenshot showing the 'ag' man page, with the help for the '-l' / '--files-with-matches' option highlighted](https://user-images.githubusercontent.com/4009681/178114290-5186bb32-dd74-4156-8bfe-d39668101466.png)
