### ISSUE TITLE
memory leak in function 'parse_options'

### ISSUE THREAD

**Issue by JoraGevorgyan** [ggreer/the_silver_searcher#1531]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
the [allocated memory](https://github.com/ggreer/the_silver_searcher/blob/a61f1780b64266587e7bc30f0f5f71c6cca97c0f/src/options.c#L340) will left without free when the function fails to [allocated another one](https://github.com/ggreer/the_silver_searcher/blob/a61f1780b64266587e7bc30f0f5f71c6cca97c0f/src/options.c#L342), because in function 'ag_malloc' it checks if memory is not allocated and exits whole program

**Comment by ulzu** [comment]
Leaks are of no importance for short running programs. They can actually improve performance as the OS reclaims the resources anyways.
