### ISSUE TITLE
-L (--files-without-matches) option does not work as expected.

### ISSUE THREAD

**Issue by vderyagin** [ggreer/the_silver_searcher#206]
`ag -L 'foobarbaz'` just prints all filenames regardless of whether they contain match for a given search string or not.

Version 0.14.

**Comment by jasonkarns** [comment]
This is still an issue in 0.32.0. can this be reopened?

**Comment by blueyed** [comment]
@jasonkarns 
Confirmed.
It seems to list all files where the pattern does not match on any line.  E.g. `ag -L 'e|a|o|u|i'` will print much less.
I suggest creating a new issue for this.  Please link to here from it.

**Comment by jasonkarns** [comment]
@blueyed #238 is a dupe of this and still open. Maybe best to take discussion there?
