### ISSUE TITLE
ag fails to run if git is not installed

### ISSUE THREAD

**Issue by karbak** [ggreer/the_silver_searcher#213]
Line 442 of src/options.c (a popen of git) assumes the executable is available on every machine "ag" is run. Every invocation fails with a "sh: git: command not found" if the executable is not found on the user's path.

**Comment by eproxus** [comment]
Is there a fix for this? You still can't use The Silver Searcher without Git in Ubuntu.

**Comment by ggreer** [comment]
Maybe Ubuntu ships an old version of ag? The latest version definitely works without git.

**Comment by eproxus** [comment]
So the issue should be closed?

**Comment by amfarrell** [comment]
The version in the debian repository runs even if git is not installed, but it prints "sh: 1: git: not found" to stderr.

To reproduce:
- Create an ubuntu 14.04 VM, or find an ubuntu machine without git.
- Run `apt-get install silversearcher-ag`
- run echo "aaasssdddfff" > ./here
- run `ag aaasssdddfff`

**Comment by ggreer** [comment]
Yeah, this seems like an issue for Debian or Ubuntu packaging people. It's been two years nice it was fixed in ag.

Sorry I can't do anything else about this.
