### ISSUE TITLE
"Fuzzy" matching

### ISSUE THREAD

**Issue by epitron** [ggreer/the_silver_searcher#220]
I just discovered fuzzy regexps tonight, and I know exactly which program they belong in. :)

They've been under development since 1988, and the state of the art in this area is this library: https://github.com/laurikari/tre/

The TRE library comes with the `agrep` tool, which supports fuzzy regexps. From the manpage:

> **SYNOPSIS**
> `agrep [OPTION]...  PATTERN [FILE]...`
> 
> **DESCRIPTION**
> Searches  for  approximate  matches  of  PATTERN in each FILE or standard input.
> 
> Example: `agrep -2 optimize foo.txt` outputs all lines in  file  'foo.txt'  that match "optimize" within two errors. (e.g. lines which contain "optimise", "opt‐mise", and "opitmize" all match.)

More background info: http://en.wikipedia.org/wiki/Agrep

`ag` should totally have `agrep` functionality. It's only fitting! ;)

**Comment by hunterboerner** [comment]
status?

**Comment by ggreer** [comment]
Probably never. It adds another dependency and almost nobody wants it. Sorry. :/

**Comment by epitron** [comment]
What if it was an option (eg: `--fuzzy`), and it was only compiled in if the TRE library was found?
