### ISSUE TITLE
Search hidden files and dirs by default

### ISSUE THREAD

**Issue by vaughnkoch** [ggreer/the_silver_searcher#24]
There are some dot-dirs that I would like to search, but ag doesn't seem to support specifying them - it's all or nothing.
For example, I'd like to always search my .ipython directory.

-u ignores .gitignore and .agignore, which isn't what I want either since it's all or nothing.

What would be really useful is for ag to search all dotfiles and dotdirs by default, except the ones in .gitignore and .agignore.

Thanks, awesome tool so far.  Love the speed improvements over ack.
OSX Lion, ag version 0.1.1

**Comment by breerly** [comment]
FWIW, I added this to my profile:

```
alias ag='ag --hidden'
```

**Comment by luochen1990** [comment]
@breerly I also think that search hidden files should be the default behavior, if somebody want to change this behavior, he just need to add .* into .agignore

**Comment by silverwind** [comment]
I don't think dotfiles should be searched by default because of `.git` but `.ignore` should have the ability to accept negated pattern like `!.*` which would essentially act the same as `--hidden` but in a portable manner.

**Comment by stherold** [comment]
I put this alias in my `.zshrc` which is exactly what I want: Searching .env files that are ignored in my .gitignore and exclude uninteresting directories:


```
alias ag="ag --hidden --skip-vcs-ignores --ignore=\"*Library*\" --ignore=\"*.gem*\" --ignore=\"*.build*\" --ignore=\"*.git*\""
```
