### ISSUE TITLE
colon as final separator is bad

### ISSUE THREAD

**Issue by towolf** [ggreer/the_silver_searcher#308]
I like `filename:linenumber:columnnumber`, but appending a (third) final colon makes it hard to select the triple with a double click.

I use this: http://www.vim.org/scripts/script.php?script_id=2184

I opens the file at the line number and column. 

I can just double click

`iwinfo/src/iwinfo_madwifi.c:754:35`

and go `vi`, `<middle paste>`

But with a colon it will select too much on double click:

`iwinfo/src/iwinfo_madwifi.c:710:21:int`

Here’s an admittedly slghtly sloppy screencast:

![record](https://f.cloud.github.com/assets/345210/1751023/98d1dc9e-65c5-11e3-81bb-c7d8573d8eb2.gif)

**Comment by richq** [comment]
@towolf Seems like the regular expression in the file_line plugin is too strict, requiring the : to be at the end of the line. If you remove the $ from the regexp it works fine, the name:line:[column:] can be followed by other chars and it'll find what it needs. This patch to file_line.vim:

```
@@ -16,7 +16,7 @@
        endif
 
        " Accept file:line:column: or file:line:column and file:line also
-       let names =  matchlist( file, '\(.\{-1,}\):\%(\(\d\+\)\%(:\(\d*\):\?\)\?\)\?$')
+       let names =  matchlist( file, '\(.\{-1,}\):\%(\(\d\+\)\%(:\(\d*\):\?\)\?\)\?')
 
        if empty(names)
                return
```

**Comment by towolf** [comment]
Thanks @richq, in the meantime it turned out that `file:line`, which is a nifty plugin, interacts badly with other plugins. Hence I’ve disabled it.

I’ll just close this then.
