### ISSUE TITLE
context line printing wrong when reading from a pipe

### ISSUE THREAD

**Issue by jjhart** [ggreer/the_silver_searcher#347]
Tested with both ag 0.14 and ag 0.19.2 on OS X Mountain Lion & Mavericks

It's a somewhat understandable behavior, but other related tools (grep) do this correctly.

``` bash
# test setup
$ for f in a b c; do echo $f; done > test.txt
$ cat test.txt
a
b
c

# correct:
$ ag -B1 b test.txt
1-a
2:b

# correct:
$ ag -C1 b test.txt
1-a
2:b
3-c


# bug in -B handling:
$ cat test.txt | ag -B1 b
b

# bug in -C handling:
$ cat test.txt | ag -C1 b
b
:
```

(yes, that's a weird ":" printed at the end)

**Comment by joachim-n** [comment]
This is still an issue in the latest version, 0.29.1.

**Comment by grekko** [comment]
I can reproduce this too w/ version 0.30.0.

```bash
$ echo "A\nB\nC" > test.txt
$ cat test.txt
A
B
C
```

Using grep (works as expected):
```
$ cat test.txt|grep -C1 B
A
B
C
```

Using ag (0.30.0, does not work):
```
$ cat test.txt|ag -C1 B
B

```

Any updates on this?

**Comment by DXist** [comment]
+1. Warning about unsupported before/after flags for stdin stream will work for me.

**Comment by cemeyer** [comment]
@jjhart Reading the entire stream into a buffer and then searching that as a file is exactly what is done for zipped files, for example.  Gzip/bzip/xz files are essentially streams.

**Comment by premek** [comment]
+1 Related: #869
