### ISSUE TITLE
gitignore globs not working for files in in subdirectories

### ISSUE THREAD

**Issue by jason0x43** [ggreer/the_silver_searcher#364]
In my gitignore, I have

<pre>
*.js
</pre>

When I run `ag` in debug mode from my project root, I see:

<pre>
...
DEBUG: added regex ignore pattern *.js
...
DEBUG: file /Application.js ignored because name matches regex pattern */*.js
...
DEBUG: pattern */*.js doesn't match file /binding/Error.js
...
</pre>

Files in the project root match, but not files in subdirectories. However, a simple file glob rule should apply in subdirectories (by git semantics, at least). Am I missing something?

**Comment by wende** [comment]
I don't believe this has been fixed by #401. As far as I'm aware ag still doesn't respect nested `.gitignore`s
