### ISSUE TITLE
./build.sh fails with an error message.

### ISSUE THREAD

**Issue by chbarts** [ggreer/the_silver_searcher#369]
Running ./build.sh fails with the following error message:

```
./configure: line 3937: syntax error near unexpected token `PCRE,'
./configure: line 3937: `PKG_CHECK_MODULES(PCRE, libpcre)'
```

I have all of the libraries (on Ubuntu Precise) and should meet all the requirements.

**Comment by ernstki** [comment]
Simply having `pkg-config` installed isn't sufficient on all systems. On CentOS 6, for example, the OS-provided `pkg-config` (v0.27.1) will yield this syntax error every time.

Building and installing  pkg-config-0.29.2, then making sure _that_ `pkg-config` was ahead of the OS's version in my `$PATH` was what finally worked for me.
