### ISSUE TITLE
How can I use ag with xargs?

### ISSUE THREAD

**Issue by ysheng26** [ggreer/the_silver_searcher#423]
I'm trying to pipe the result of `ag` to another command, but it seems that `ag` is not working well with `xargs`

```
test file: test.txt
shengy
otherstuff
```

`ag -l shengy` will output `test.txt` correctly, but `ag -l shengy | xargs cat` will report `: No such file or directory`.

Btw, if there is spaces in the path, should I use `xargs`'s `-0` option? I'm not sure if this works since it doesn't work even if there are no spaces in the path.

**Comment by retorquere** [comment]
I'm still not clear how to use this. I tried

```
ag allowDup -0 | xargs -0 vim
```

but I'm getting

```
Vim: Warning: Input is not from a terminal
```

**Comment by krazylegz** [comment]
Take a look at the `-l` option to `ag` so that it only prints file names.

**Comment by retorquere** [comment]
If I do this

```
ag addCreators -l -0 | xargs -0 vi
```

I still get

```
Vim: Warning: Input is not from a terminal
```

vi does start up, but after vi exits, the terminal no longer displays newlines (enter does move the cursor forward, but everything is on a single line).

**Comment by retorquere** [comment]
Oops, found the culprit: https://superuser.com/questions/336016/invoking-vi-through-find-xargs-breaks-my-terminal-why
