### ISSUE TITLE
There should be a way to search using unlimited depth

### ISSUE THREAD

**Issue by cdow** [ggreer/the_silver_searcher#425]
Sometimes it can be difficult to determine how deep a directory goes.  Also, the error messages about depth can easily be lost in search results.  It would be nice if there was a way to specify unlimited depth for searches for these cases.

I was thinking this could be accomplished by specify a negative number for depth.  If this sounds good, I would be happy to submit a patch.

**Comment by ggreer** [comment]
Fixed in #539.

**Comment by cdow** [comment]
Thanks!
