### ISSUE TITLE
.gitignore globs broken when specifying an absolute path

### ISSUE THREAD

**Issue by jdelStrother** [ggreer/the_silver_searcher#448]
Hi there - I'm using ag 0.23.0 with unite.vim.  I have a gitignore file at `/my/directory/.gitignore`, which contains a line `public/assets*`.  When I run

``` bash
  ag -g "application*" /my/directory
```

, it includes files in `/my/directory/public/assets-production` - which it shouldn't, given the .gitignore line.

Strangely, if I use a relative path for the last argument - 

``` bash
  ag -g "application*" .
```

,  .gitignore gets parsed correctly, and files in public/assets-production are filtered out.  Similarly, if I explicitly list `public/assets-production` in my .gitignore, that will also filter those results out, even when using the absolute path.

Bug, or am I missing something?

**Comment by vmrob** [comment]
Curiously, the fix here actually breaks the following search:

```
$ tree -a
.
└── test
    ├── .gitignore
    └── foo

1 directory, 2 files
$ cat test/.gitignore 
/foo
$ cat test/foo
bar
$ ag bar test
test/foo
1:bar
```

Reverting to `ignores *ig = init_ignore(root_ignores, paths[i], strlen(paths[i]));` fixes it but introduces breaks this usage. I suppose the issue centers around the handling of absolute/relative paths and ignore patterns from root to those paths.

**Comment by deiwin** [comment]
I'm still seeing something similar. When an absolute path is used instead of a relative one, then the local `.gitignore` will be ignored. The global gitignore is still considered in both cases.
