### ISSUE TITLE
Can't search for dollar sign, even when escaped.

### ISSUE THREAD

**Issue by BeekeeperAlex** [ggreer/the_silver_searcher#482]
I tried searching my project for the angularJS service `$timeout` using ag. I tried the following:

> $ ag "\$timeout"

However, it acts like there were no results. In grep if I type this:

> $ grep -rl "\$timeout" ./

It will find them all. Naturally I'd prefer to use my lightning fast silver searcher over grep ;)

Any idea why I can't escape the dollar sign? I think it's still using it as the end of line regular expression even when escaped.

**Comment by embix** [comment]
Is there by any chance a switch to automatically escape dollar signs et al. when using a password file via `-f`?

**Comment by embix** [comment]
Is there by any chance a way to automatically escape dollar signs et al. when reading passwords from a file using `-f`?
