### ISSUE TITLE
bails before reaching --max-count; "|wc -l" differs from grep -c

### ISSUE THREAD

**Issue by unhammer** [ggreer/the_silver_searcher#483]
ag bails out with "Too many matches" before reaching --max-count:

```
$ grep -c a /usr/share/dict/words 
61444

$ ag --max-count 61444 a /usr/share/dict/words |wc -l
ERR: Too many matches in /usr/share/dict/words. Skipping the rest of this file.
48018

$ ag --max-count 61445 a /usr/share/dict/words |wc -l
ERR: Too many matches in /usr/share/dict/words. Skipping the rest of this file.
48019

$ ag --max-count 61446 a /usr/share/dict/words |wc -l
ERR: Too many matches in /usr/share/dict/words. Skipping the rest of this file.
48019
```

And if we give a really high --max-count, it gets even more confusing:

```
$ ag --max-count 9999999 a /usr/share/dict/words |wc -l
62226
```

That last one is somehow more than what grep -c reported – who should I trust?

**Comment by dannguyen** [comment]
FWIW, I'm still getting the problem of `max-count` bailing out too early, i.e. the error:

            Too many matches in /tmp/whatever.txt Skipping the rest of this file.

When using `ag --max-count 1 /tmp/whatever.txt`.

This is on OS X 10.11 using 0.31.0

**Comment by nnungest** [comment]
I am as well. with a simple ```--max-count 1```
```
ag version 2.2.0

Features:
  +jit +lzma +zlib
```
