### ISSUE TITLE
Static linking against libpcre?

### ISSUE THREAD

**Issue by nathansobo** [ggreer/the_silver_searcher#49]
Hi Geoff,

We're hoping to embed ag into an application (as it's own binary, that we interact with as a child process when needed). We've noticed it depends on the pcre dynamic library being available on the system. Presumably it's possible to statically link against libpcre.a instead? I'm completely unversed in GNU autotools, but I started reading about it last night. If it's a simple change to statically link, maybe you could just tell me what to change? But otherwise I'll keep studying :-). Are there any other obstacles you can think of that would preclude redistributing a binary that runs on modern versions of OS X? Thanks!

**Comment by lifenjoiner** [comment]
Comment for anyone looks up ...

Came across the 'same' thing on Windows: static link pcre.

`-static` doesn't help.
Try add `-DPCRE_STATIC` to your `CFLAGS`. It is a trick of `PCRE` ;p

Read `pcre.h`, you will see:
```c
#if defined(_WIN32) && !defined(PCRE_STATIC)
#  ifndef PCRE_EXP_DECL
#    define PCRE_EXP_DECL  extern __declspec(dllimport)
#  endif
#  ifdef __cplusplus
#    ifndef PCRECPP_EXP_DECL
#      define PCRECPP_EXP_DECL  extern __declspec(dllimport)
#    endif
#    ifndef PCRECPP_EXP_DEFN
#      define PCRECPP_EXP_DEFN  __declspec(dllimport)
#    endif
#  endif
#endif

/* By default, we use the standard "extern" declarations. */

#ifndef PCRE_EXP_DECL
#  ifdef __cplusplus
#    define PCRE_EXP_DECL  extern "C"
#  else
#    define PCRE_EXP_DECL  extern
#  endif
#endif
```
