### ISSUE TITLE
Support for command-line exclude patterns ?

### ISSUE THREAD

**Issue by gjtorikian** [ggreer/the_silver_searcher#51]
Sometimes, you don't want to exclude based on a _.*ignore_ file. You may just want to exclude certain patterns based on a one-time only search. For example:

`ag var --exclude-files={*.js, *.markdown}`

would exclude files based on those extensions.

On a directory level:

`ag var --exclude-dirs={lib, src}`

would not enter directories that match _lib_ or _src_.

For extra ice cream bonus points, wildcard matching would be awesome: `s*rc*` excludes _src_ and _source_.

I know you like image macros:

![](http://netanimations.net/dog32.gif)

**Comment by sigmavirus24** [comment]
Now that there's an `--ignore-dir` can this be closed? Or is there still more work for this?

**Comment by d0u9** [comment]
Well. if I want to skip `pdf` `doc` `jpg` `png` `out` `exe` etc, does it means I need to append more and more `--ignore` options? I hope `--ignore` can support regex, then I can do that gracefully, i.e. `--ignore "(pdf|doc|jpg|png|out|exe|)$"`.

**Comment by brandonsturgeon** [comment]
Any update on this? I get enormous results from doc/ folders that fill up my entire terminal.

**Comment by cevaris** [comment]
Seems to be an `--ignore` flag now that works well

`ag  searchTerm  myDirToSearch --ignore js --ignore css --ignore "*list"`
