### ISSUE TITLE
Cannot build on CentOS 5.10

### ISSUE THREAD

**Issue by dcblack** [ggreer/the_silver_searcher#525]
% 
% uname -a
Linux localhost.localdomain 2.6.18-371.12.1.el5 #1 SMP Wed Sep 3 16:22:34 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
% sudo yum -y groupinstall "Development Tools"
...
% sudo yum -y groupinstall "Development Tools"
...
% git clone git@github.com:ggreer/the_silver_searcher.git
...
% cd the_silver_searcher
%  ./build.sh 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking whether make supports nested variables... yes
**./configure: line 3931: syntax error near unexpected token `PCRE,'
./configure: line 3931: `PKG_CHECK_MODULES(PCRE, libpcre)'**

**Comment by martinlindhe** [comment]
ggreer: i hit the same error, on debian lenny. installing pkg-config solved my issue

**Comment by ggreer** [comment]
Cool. I figure this issue is due to missing deps. Closing.

**Comment by ernstki** [comment]
Simply having `pkg-config` installed isn't sufficient on all systems. On CentOS 6, for example, the OS-supplied `pkg-config` (v0.27.1) will throw up this syntax error every time.

Building and installing  pkg-config-0.29.2, then making sure _that_ `pkg-config` was ahead of the OS's version in my `$PATH` was what finally worked for me.
