### ISSUE TITLE
Is it possible to add ag to MSYS2

### ISSUE THREAD

**Issue by ShuguangSun** [ggreer/the_silver_searcher#535]
Is it possible to add ag to MSYS2? https://github.com/Alexpux/MSYS2-packages
It seems need a PKGBUILD, but I don't know how to do it.

**Comment by oscarfv** [comment]
`ag` already is on MSYS2. It has some serious problems when running on the MSYS2 default shell, though, because `ag` behavior depends on if `stdin` is a pipe or a tty, and mintty makes `ag` think it is working on a tty. Use `--search-files`. Otherwise it works.

**Comment by Swoorup** [comment]
@oscarfv Is it possible to fix this behaviour?
