### ISSUE TITLE
ag for multiple patterns

### ISSUE THREAD

**Issue by c02y** [ggreer/the_silver_searcher#551]
For example, I got files which one or more of them contains:

```
...
one
two three
four
five
...
```

I want to know which files contains `one` AND `four`(which may be in the different lines) at the same time, 
I can use `grep -e one -e four /dir/files*` to get this, can I do that using `ag`?

**Comment by danthegoodman** [comment]
For others who would like something similar, I accomplished this by chaining multiple ag calls together using `-l` and `xargs`:
```
ag -l one | xargs ag four
```

This has the downside of only highlighting the term in the last query. If you want to hightlight both, this will work:

```
ag -l one | xargs ag -l four | xargs ag 'one|four'
```

**Comment by c02y** [comment]
It seems

    ag -l one | xargs ag -l four | xargs ag 'one|four'

only prints the matching lines number but not the file name if one file matches the pattern.

**Comment by HaleTom** [comment]
I needed to add `--no-color` as `ag` writes colours through pipes otherwise, and this was preventing the subsequent `ag` matching properly.

```
ag -l --no-color one | xargs ag -l --no-color four | xargs ag --filename 'one|four'
```

Bug #1164 prevents printing the filename if only one filename is passed to the final `ag`.

**Comment by CMCDragonkai** [comment]
What about when you want files that mention 2 words (but those 2 words can be anywhere in the file).

**Comment by pabloab** [comment]
@HaleTom on ag version 0.31.0 is `--nocolor` (without the dash).

**Comment by adrianTNT** [comment]
> For others who would like something similar, I accomplished this by chaining multiple ag calls together using `-l` and `xargs`:
> 
> ```
> ag -l one | xargs ag four
> ```
> 

!! careful about this, I noticed if used like this `ag -li word1 my_directory/ | xargs ag -li word2`, works nicely, but **if** first part finds nothing, second part it will search in current directory, **not** in `my_directory`, since first part will output blank, it will simply run `ag li word2` with no file to search into = current directory; and you cannot include the path in second part, it would re-do the search in that directory.

**Comment by b0o** [comment]
I wrote a little script which integrates some of the suggestions here and provides more features: [aag](https://gist.github.com/b0o/f0759c84af6ef773a37a499fdb1c05af).

**Comment by peterbabic** [comment]
Why -e is not implemented, BTW? Cluttering?
