### ISSUE TITLE
Discrepancy between grep -o and ag -o

### ISSUE THREAD

**Issue by commonquail** [ggreer/the_silver_searcher#554]
927814d3c287e0fd288865a4e84e4b2ccabf8754 (related: #552, #454) adds an `--only-matching` option.

```sh
mkdir o-test && cd o-test && \
    echo "hello hello" > world && \
    grep -o hello world && \
    ag -o hello world \
    && cd .. && rm -r o-test
hello
hello
1:hellohello
```
`grep` prints each match on a separate line, `ag` prints matches on the same line. I figure this is an oversight, but if not, it should probably be documented. I don't know how `ack` compares.

**Comment by ggreer** [comment]
Thank you for reporting this and demonstrating grep and ack's behavior. I've merged the fix into master. It will be in the next release.
