### ISSUE TITLE
.gitignore entries not working when file is in a subdirectory

### ISSUE THREAD

**Issue by amagee** [ggreer/the_silver_searcher#568]
Even a simple `.gitignore` file with one line like

    *.txt

Will properly ignore files in the root directory, but not in subdirectories.

Eg:

    $ echo hello > hello.txt
    $ ag hello  # No gitignore -- fine
    hello.txt
    1:hello

    $ echo '*.txt' > .gitignore
    $ ag hello  # In gitignore, fine

    $ mkdir subdir
    $ mv hello.txt subdir
    $ ag hello  # file should still be ignored but isn't anymore
    subdir/hello.txt
    1:hello

`git status` correctly ignores the file. 

The same problem occurs if I use `.hgignore` or `.agignore`. This seems to be a recent problem.

I'm using `ag` version 0.22.0.

**Comment by amagee** [comment]
Seems even explicitly passing `--ignore` does not work. For example:

    $ ag --ignore='*~' stuff

Will still match files ending tildes in subdirectories. (I've tried various ways of representing the pattern there as I'm not sure what kind of syntax is expected, but nothing seems to work.)

**Comment by ggreer** [comment]
Have you tried the latest version of ag? (0.28.0)

**Comment by amagee** [comment]
Ah, it works in 0.28.0.. must be an issue in 0.22.0 which unfortunately is still current in the default Ubuntu repos.

**Comment by ggreer** [comment]
In the future, please try the latest version of ag before opening an issue.
