### ISSUE TITLE
The build script is missing from the tarballs

### ISSUE THREAD

**Issue by silb** [ggreer/the_silver_searcher#569]
The build script `build.sh` is missing from the tarballs at <http://geoff.greer.fm/ag/>.

This means that the build instructions in `README.md` doesn't apply to the source code from the tarballs.

**Comment by mcphail** [comment]
As far as the missing build script is concerned, this is a feature and not a bug ;) . End users should not have to install autotools to build and install the package and should use the conventional `./configure && make && make install` path. I agree the Readme should reflect this.

**Comment by ggreer** [comment]
I've updated the readme. Thanks for letting me know about this.
