### ISSUE TITLE
Ag doesn't seem to properly print to stdout (unless I use --ackmate) when in node script

### ISSUE THREAD

**Issue by gjtorikian** [ggreer/the_silver_searcher#57]
This one baffled me and a colleague for a good 45 minutes: http://screencast.com/t/DCog6zuFRhO

Basically, I can run ag on the command line. Great! I actually want to run it as part of a node script. I wrapped up the command in a spawn function, and waited to listen for data events on stdout. I also waited for error and exit events.

Except, nothing ever came out.

When I added the `--ackmate` option to the script, I got my results. I would prefer not to use this option, though, as I don't want it. 

Looking at the source, I see everyone doing `printf()` all the same. I'm not sure what's going on. This is the absolute latest source from the repo.

Edit: I was running Node v0.6.18, and [here's a gist of my file](https://gist.github.com/3563277).

![](http://blastr.com/assets_c/2011/01/PrincessLeiaHologram012511-thumb-550x295-55988.jpg)

**Comment by teamon** [comment]
I just got bitten by this when using:

```bash
while read -r x; do
  ag "..."
done <<< "..."
```

A message to stderr "searching stdin" would be nice to have.
