### ISSUE TITLE
Missing signature for the 0.27.0 release

### ISSUE THREAD

**Issue by silb** [ggreer/the_silver_searcher#570]
I get an HTTP 404 not found for the link to <http://geoff.greer.fm/ag/releases/the_silver_searcher-0.27.0.tar.gz.asc> from <http://geoff.greer.fm/ag/>.

**Comment by ggreer** [comment]
Oops. It's fixed now. I accidentally forgot to ascii-armor that signature, so it was a .gpg file, not a .asc.
