### ISSUE TITLE
Searching for "||=" results in ag being OOM killed

### ISSUE THREAD

**Issue by YorickPeterse** [ggreer/the_silver_searcher#572]
When searching for `||=` ag ends up being OOM killed by the kernel. A simple example:

```
mkdir /tmp/foo
cd /tmp/foo
echo 'foo ||= bar' > test.txt
ag '||=' .
```

This occurs at least on Arch Linux (`Linux tuxbook 3.17.3-1-ARCH #1 SMP PREEMPT Fri Nov 14 23:13:48 CET 2014 x86_64 GNU/Linux` in case it helps) using ag version 0.28.0.

**Comment by umanwizard** [comment]
The issue here is that zero-length matches put Ag into an infinite loop.

**Comment by ggreer** [comment]
Thanks to @umanwizard, this is fixed. A zero-length match is rather confusing when it's printed out, but who am I to second-guess someone's regex?

**Comment by umanwizard** [comment]
FYI @YorickPeterse , `ag ||=` probably doesn't do what you want, if you are expecting it to find that literal string in files. You can pass the `-Q` flag to enable literal searching, rather than interpreting `||=` as a (very strange) regex.

**Comment by YorickPeterse** [comment]
@umanwizard Hm, you're right, it didn't occur to me this would search for it as a regex. Thanks for looking into this!
