### ISSUE TITLE
Naming of --line-numbers and --no-numbers options

### ISSUE THREAD

**Issue by padde** [ggreer/the_silver_searcher#590]
The `--line-numbers` and `--no-numbers` options are named inconsistently. Shouldn't they be called `--[no]numbers`, just like `--[no]heading`, `--[no]break` and `--[no]group`? I suggest keeping the oddly named cousins around.

Maybe we could print a deprecation warning to stderr, then eventually remove them in the future.

**Comment by ggreer** [comment]
This makes sense to me. I'm not sure why I messed up those options.

**Comment by padde** [comment]
Thanks for your work, looks great!
