### ISSUE TITLE
Omit filename output

### ISSUE THREAD

**Issue by padde** [ggreer/the_silver_searcher#591]
Related to #400.

For use in scripting it would be helpful to be able to strip all output except the actual match. I know I can use `--nogroup -o` and then pipe the output through `cut` in order to extract the matches (first example has matches highlighted with brackets to show the structure):

```
~$ ag 'f\w+'
foo.txt
1:[foo] [foobar]
4:[foobar]

~$ ag --nogroup -o 'f\w+' | cut -d: -f4
foo
foobar
foobar
```

Still, I think it would be much prettier and less fragile if we could configure all parts of the output. Some parts are already there, for example the `--no-numbers` option, so only the file name remains:

```
~$ ag --nogroup --no-numbers -o 'f\w+' 
foo.txt:foo
foo.txt:foobar
foo.txt:foobar
```

I could imagine a `--nofilename` option that implies the ommission of file name, line and column numbers, i.e. only printing the match itself, nothing else.

```
~$ ag --nogroup --nofilename -o 'f\w+' 
foo
foobar
foobar
```

it should also work without `--nogroup`

```
~$ ag --nofilename -o 'f\w+' 
foo
foobar
foobar
```

and without `-o`

```
~$ ag --nofilename 'f\w+' 
foo foobar
foobar
```

**Comment by ggreer** [comment]
`--nofilename` is added in https://github.com/ggreer/the_silver_searcher/commit/526e18b690a59abad4d73eb243ee6670b87faadd

It'll be in the next release. Thanks for the suggestion.

**Comment by padde** [comment]
@ggreer again, thanks for your quick reaction, really appreciated!
