### ISSUE TITLE
gitignore absolute paths do not work when gitignore is in a subdirectory

### ISSUE THREAD

**Issue by ctrueden** [ggreer/the_silver_searcher#595]
For `.gitignore` files deeper than the current working directory, absolute paths are (at least partially) not anchored relative to the `.gitignore` file, but rather to the CWD.

Here is a patch to the `ignore_abs_path` cram test which illustrates the issue: https://github.com/ctrueden/the_silver_searcher/commit/4f1399723ecb6db069af455b2f37ee38b7e3ddab

**Comment by ggreer** [comment]
This is a duplicate of #144.

**Comment by ctrueden** [comment]
My reading of #144 is that it refers to a scenario where `ag` is invoked from a subdirectory of a Git repository root. However, this issue refers to a different scenario: `ag` invoked from a _super_-directory of one or more Git repository roots. So I'm not sure it's really a duplicate, though the bugs may be related.

**Comment by ggreer** [comment]
You're right. Reopened.

**Comment by mcphail** [comment]
Is this the same issue as #285?

**Comment by ctrueden** [comment]
@mcphail Upon initial inspection, looks like it, yeah. Same as #285 (and #309). Closing as duplicate, although I hope the unit test patch is still useful for testing any fix.
