### ISSUE TITLE
Possible regression in 0.29.0: .gitignore

### ISSUE THREAD

**Issue by geoffharcourt** [ggreer/the_silver_searcher#598]
While investigating https://github.com/thoughtbot/dotfiles/pull/338, I confirmed a difference in behavior between 0.28.0 and 0.29.0.

We have this line in our `.gitignore`:

```shell
*.DS_Store
```

In 0.29.0, this results in any folder that contains a `.DS_Store` file being completely excluded from search results. If I fall back to v0.28.0, I get these results back.

As @danielnolan mentions in the above issue, removing the `*` from the `.DS_Store` reference fixes the behavior, but I'm not sure if that has other impact on Git or Ag that I'm missing. It also seems like it's a mismatch between that Git is ignoring and what Ag ignores.

**Comment by ggreer** [comment]
Thanks for the bug report. I'm pretty sure this is related to my new file extension detection stuff. I'll look into it soon.

**Comment by drn** [comment]
Thanks for looking into this! I can confirm this issue as well. I was having issues searching against the main directory of a project and traced it back to the `*.DS_Store` in my global `.gitignore`.

**Comment by ggreer** [comment]
Well that was an embarrassing bug. I've tagged a patch release (0.29.1). Sorry about that.
