### ISSUE TITLE
Pattern is detected as option when pattern starts with "--"

### ISSUE THREAD

**Issue by eksperimental** [ggreer/the_silver_searcher#604]
I'm trying to search for a regular string in my directory

```bash
$ ag "--no-start" ./
ag: unrecognized option '--no-start'
```
```bash
$ag --literal "--no-start" ./
ag: unrecognized option '--no-start'
```

```bash
ag --literal "--no-start" ./
ag: unrecognized option '--no-start'
```

hmmm

```bash
$ag --literal '--no-start' ./
ag: unrecognized option '--no-start'
```
ok. this way is the only one that  works
`$ ag "\--no-start" ./`
because 
`$ ag --literal "\--no-start" ./` or `$ ag --literal '\--no-start' ./` wont

as far as I know, "--"  has no special meaning in PREG.
it's clearly ignoring the quotes and taking it as an option, not as an pattern

thanks for reading

**Comment by charmander** [comment]
```
ag -- --no-start
```

**Comment by eksperimental** [comment]
nice.. is that documented?

**Comment by ggreer** [comment]
That's just how shells work.

**Comment by charmander** [comment]
It’s a feature of `getopt`:

> By default, `getopt()` permutes the contents of argv as it scans, so that
> eventually all the nonoptions are at the end. Two other modes are also
> implemented. If the first character of `optstring` is `'+'` or the
> environment variable `POSIXLY_CORRECT` is set, then option processing stops
> as soon as a nonoption argument is encountered. If the first character of
> `optstring` is `'-'`, then each nonoption `argv`-element is handled as if it
> were the argument of an option with character code 1. (This is used by
> programs that were written to expect options and other argv-elements in any
> order and that care about the ordering of the two.) The special argument
> `"--"` forces an end of option-scanning regardless of the scanning mode.

**Comment by eksperimental** [comment]
Thanks a lot. I have been using the shell for years and this is the first time i encounter this situation.
