### ISSUE TITLE
ag -a vs. ag

### ISSUE THREAD

**Issue by Wikunia** [ggreer/the_silver_searcher#605]
Hey guys,

it isn't really an issue but I don't know where I should ask this.
What is the difference between `ag -a` and `ag` ? And why is there a difference? 
I think it's a bit strange when you want to search inside an directory with hundreds of php files and 
`ag print` doesn't return anything but `ag -a print` does.

**Comment by charmander** [comment]
Are the hundreds of PHP files ignored by a `.gitignore`, `.agignore`, etc.?

**Comment by Wikunia** [comment]
No I don't have a `.agignore` file and they are all part of a git repo without a `.gitignore` file.

**Comment by charmander** [comment]
What are their names?

**Comment by Wikunia** [comment]
`sys/veranstaltung/uebung.class.php` is one of the files. Why do you ask?

**Comment by Wikunia** [comment]
Damn I am so sorry @charmander there was a `.gitignore` file but the php files are inside the `.gitignore` using a `!` so they shouldn't be excluded. Hope that helps.

**Comment by charmander** [comment]
Oh, that would be #168.

**Comment by ggreer** [comment]
Thanks for linking to the original issue. Closing this one because it is a duplicate.
