### ISSUE TITLE
-l with path and without pattern

### ISSUE THREAD

**Issue by siadat** [ggreer/the_silver_searcher#607]
In ack, we could list all ruby files in /dir/ using:

    ack -lf --ruby -- /dir/

Note that no pattern is give. However, I cannot do the same in ag, because ag parses /dir/ as a regular expression. The closest thing I could do in ag is to:

    cd /dir/ && ag -l --ruby

**Comment by charmander** [comment]
The default query when using `ag -l --ruby` [is just `.`][1], so you could use that.

    ag -l --ruby . /dir/


  [1]: https://github.com/ggreer/the_silver_searcher/blob/bb18d020ece15ef04c3ab2e68bd571aa4c30421b/src/options.c#L661

**Comment by siadat** [comment]
:+1: interesting.

Also, thanks for the link. I was going to skim the code, I guess that's a good starting point.
