### ISSUE TITLE
Latest update breaks agignore

### ISSUE THREAD

**Issue by honza** [ggreer/the_silver_searcher#609]
Given a directory with a single file `hi.min.js` with the contents of `// oranges`, I issue a search query:

```
$ ag orange
hi.min.js
1:// oranges
```

My `$HOME/.agignore` has:

```
*.min.js
```

This is with `0.29.1`.

**Comment by yrns** [comment]
Try `*.min.*`?

**Comment by honza** [comment]
That works, thanks!
