### ISSUE TITLE
.gitignore format not recognised

### ISSUE THREAD

**Issue by fommil** [ggreer/the_silver_searcher#633]
.gitignore allows patterns such as

```
**/foo-bar
```

to mean any file/directory under any subdirectory with this name.

However, `ag` (0.28.0) is not able to recognise these exclusions. As a workaround, do it without `**/`

**Comment by juanibiapina** [comment]
Also doesn't seem to recognise these:

```
log/*.log
log/*.*
```

**Comment by shioyama** [comment]
Would be great if this could be fixed! Those log files sure clutter the search results...
