### ISSUE TITLE
No --output Option

### ISSUE THREAD

**Issue by jacobp100** [ggreer/the_silver_searcher#642]
See ack for implementation.

**Comment by jacobp100** [comment]
Is this won't fix, on it's way, or the bug report is invalid?

**Comment by ggreer** [comment]
I put approximately as much effort into this issue as you did.

**Comment by jacobp100** [comment]
https://github.com/ggreer/the_silver_searcher/issues/513

If issues weren't closed if they were just unlikely to be implemented, it would have been easier to find.
