### ISSUE TITLE
Does not return all matches

### ISSUE THREAD

**Issue by neojski** [ggreer/the_silver_searcher#661]
That was very surprising for me:

```
$ ag -i box_enabled       
js/svg.js
93:svg.BOX_ENABLED = true;
96:  if(!svg.BOX_ENABLED){

js/circles.js
209:        svg.BOX_ENABLED = false;
223:      svg.BOX_ENABLED = true;
625:  svg.BOX_ENABLED = false;
639:  svg.BOX_ENABLED = true;
```

But

```
$ ack -i box_enabled
dist/js/profiler.js
367:        svg.BOX_ENABLED = false;
381:      svg.BOX_ENABLED = true;
783:  svg.BOX_ENABLED = false;
797:  svg.BOX_ENABLED = true;
6256:svg.BOX_ENABLED = true;
6259:  if(!svg.BOX_ENABLED){

js/bundle.js
247:        svg.BOX_ENABLED = false;
261:      svg.BOX_ENABLED = true;
6191:svg.BOX_ENABLED = true;
6193:  if(!svg.BOX_ENABLED){

js/svg.js
93:svg.BOX_ENABLED = true;
96:  if(!svg.BOX_ENABLED){

js/circles.js
209:        svg.BOX_ENABLED = false;
223:      svg.BOX_ENABLED = true;
625:  svg.BOX_ENABLED = false;
639:  svg.BOX_ENABLED = true;
```

fgrep finds them all and also `./dist/js/profiler.js.map` and `./js/.svg.js.swp`. If I `cd` into `dist` ag finds the map file as well.

Also it doesn't want to go too deep:
```
$ pwd
~/svg
$ ag -Q 'scale='
asdf/1234/1340547211
1:<svg xmlns="http://www.w3.org/2000/svg" xmlns:a0="info" width="144.5mm" height="60.5mm" viewBox="-12 -2761.4 144.5 60.5" a0:scale="1">
```

but

```
$ pwd
~
$ ag -Q 'scale='
nothing
```

Changing `--depth` only limits the results above (I see that it correctly limits the results if I set `--depth=2`).

I'm using archlinux.

Are there any strange default configs that make this happen or is this a legitimate bug?

**Comment by ggreer** [comment]
Are some of those files ignored by `.gitignore`, `.agignore`, `.hgignore`, etc?

**Comment by neojski** [comment]
@ggreer, it looks that you're just right! These files were in my `.gitignore` and `ag -t` finds them. I didn't realize that `ag` ingores these files but it is in the docs so that's entirely my fault. Thanks!

By the way, from the description in the manual I wouldn't infer that `-t` ingores `.gitignore` (`-u` states it explicitly).
