### ISSUE TITLE
Pager Support (for paging through colored results)

### ISSUE THREAD

**Issue by gwittel** [ggreer/the_silver_searcher#67]
One nice feature of 'ack' is that you can set a pager so you can page through the colored result set.  It would be cool if there was a simple pager option (defaulting to less -R or -r) to display results via a pager.

**Comment by whit537** [comment]
Note that `ag` doesn't use an `~/.agrc` file by design (https://github.com/ggreer/the_silver_searcher/issues/61), so to configure this globally you should use a shell alias like so:

```
alias ag="ag --pager='less -R'"
```

**Comment by fcbertoldi** [comment]
A change that IMO improves the experience: add the less flag `-F|--quit-if-one-screen` to not page if the whole output fits the screen.

```
alias ag="ag --pager='less -RF'"
```
