### ISSUE TITLE
Wrong build instruction in README.md

### ISSUE THREAD

**Issue by vkni** [ggreer/the_silver_searcher#687]
"Building release tarballs requires the same dependencies, except for automake and pkg-config. Once you've installed the depend
encies, just run:

    ./configure
    make
    make install
"

It does not work, since there is no ./configure script in top-level directory. One should run build.sh instead.

**Comment by ggreer** [comment]
GPG-signed release tarballs are hosted on [my site](http://geoff.greer.fm/ag). They do have a configure script in the root.

**Comment by vkni** [comment]
Thanks a lot!
