### ISSUE TITLE
No way to search case-sensitively for an all-lowercase pattern

### ISSUE THREAD

**Issue by bdesham** [ggreer/the_silver_searcher#693]
Maybe I’m just reading ag’s man page and help wrong (q.v. #489), but I can’t see any way to search for an all-lowercase pattern while also requiring case-sensitivity. For example:

    $ ag -i "\bcb" ComPort.cpp
    41:        dcb.BaudRate        = CBR_115200;
    $ ag "\bcb" ComPort.cpp 
    41:        dcb.BaudRate        = CBR_115200;
    $ ag "\bcB" ComPort.cpp
    $ 

How can I search for an all-lowercase pattern in this manner?

*Edited to add:* I am using ag 0.30.0 on OS X 10.10.3. My filesystem is case-insensitive, although I don’t believe that’s relevant.

**Comment by ggreer** [comment]
Read the manpage or the output of `ag --help`. The flag you want is `-s`.

**Comment by bdesham** [comment]
Thanks!
