### ISSUE TITLE
Some file is skipped during searches

### ISSUE THREAD

**Issue by gkotian** [ggreer/the_silver_searcher#704]
I have a really strange issue. I have a variable called `start_time` that is declared in a file called `Active.d` and used in a file called `Downloads.d`. But when I try to search for it with `ag -w start_time src`, it only shows the occurrence in `Active.d`. If I use `grep -rw start_time src`, then it shows me all occurrences as expected.

I can't figure out why the `Downloads.d` file is skipped.

Unfortunately I can't share the source code as they are my employer's proprietary software. I tried to reduce the test case further by copying only these two files into a temporary directory, but then `ag` did not skip the `Downloads.d` file and reported all occurrences.

I'd appreciate any help on this, and would be happy to run other tests if needed.

**Comment by serialdoom** [comment]
Maybe there is something in your ingore lists (eg. .gitignore) that prevents the `Downloads.d` folder to be scanned ? Is the file in the `Downloads.d` directory listed when you do `ag -l` ?

**Comment by gkotian** [comment]
`Downloads.d` & `Active.d` are not directories, they are source files. We code in the [D programming language](http://dlang.org/).
I haven't tried `ag -l` yet though. Will try and report back.

**Comment by serialdoom** [comment]
Sorry, i totally missed the 7 times you mentioned that those `.d` things were files and assumed dirs. I'll blame the lack of coffee :\

**Comment by gkotian** [comment]
I can't for the life of me reproduce this anymore. I wonder if it was human error, but I also can't imagine what I could have done wrong.

I'm going to close this now, and reopen if I see this again (after having run `ag -l`).

Maybe it was me who was suffering from the lack of coffee :\
Sorry for the noise.
