### ISSUE TITLE
Can't print filename since version 0.25

### ISSUE THREAD

**Issue by zijianyue** [ggreer/the_silver_searcher#705]
As the screenshot shows, it can't print filename
![image](https://cloud.githubusercontent.com/assets/6119928/8408154/2dff22e2-1ea0-11e5-97da-26b83a1965f7.png)

**Comment by epmatsw** [comment]
I can't reproduce this on OSX 10.11 :(

**Comment by zijianyue** [comment]
I'm win7 x64.
