### ISSUE TITLE
Can not install it in El-Capitan!!

### ISSUE THREAD

**Issue by ahmadseleem** [ggreer/the_silver_searcher#711]
aclocal: warning: couldn't open directory ' /usr/local/share/aclocal': No such file or directory
aclocal: error: aclocal: file '/usr/local/share/aclocal/lt~obsolete.m4' does not exist

**Comment by ggreer** [comment]
Have you built ag from source on earlier versions of OS X? It looks like you don't have dependencies installed.

**Comment by fossilet** [comment]
I had the same problem and solved it.

I find the files under `/usr/local/share/aclocal` are dead links. I tried first:

`brew install libtool intltool freetype`

then `brew install ag` succeeds.

After that, even if I uninstalled `libtool intltool freetype`, `ag` can successfully install.

**Comment by ggreer** [comment]
I'll look into this when 10.11 gets closer to release. Right now, tons of things are broken in it, including homebrew.

**Comment by ahmadseleem** [comment]
It's working a while ago, BTW.
You can just do this:

 sudo chown $(whoami):admin /usr/local
- you might also use the "-R" flag.

because before most of the file there used to owned by the: "wheel" group. or some by the root user as I remeber...

You can do the same with some other files or directories in the home dir. like rubies...

That's all, I  think.
