### ISSUE TITLE
Source other ignore files from `.agignore`

### ISSUE THREAD

**Issue by geoffharcourt** [ggreer/the_silver_searcher#723]
Teams sharing dotfiles currently can't share ignore preferences but retain their own personal global overrides. An example of this would be the team having their `.agignore` configuration, and then individual team members adding their own personal preferences in `.agignore.local`.

Adding this issue to discuss if adding the ability to source further ignore files from `.agignore` to support shared and personal preferences is feasible.

**Comment by ggreer** [comment]
Did you try putting patterns in `~/.agignore`?

**Comment by geoffharcourt** [comment]
The issue I'm trying to get around is that `~/.agignore` is shared by the team, and so I was hoping to be able to declare a second file that could be sourced that would be under each team member's personal control.

**Comment by ggreer** [comment]
The `.agignore` in each person's home directory is shared?! I'm sure there must be a misunderstanding.
