### ISSUE TITLE
more newbie-friendly README

### ISSUE THREAD

**Issue by wolftune** [ggreer/the_silver_searcher#739]
Presenting this as "a better ack" is completely opaque for anyone who isn't coming from ack. I highly suggest changing this to just describe what it does and then later mention how it relates to other options / history.

**Comment by eksperimental** [comment]
I have to agree with the OP.
I think it's bad marketing tool to promote such a great tool, comparing to others.
I think the silver searcher can stand by itself.

I would mention `ack` as I would mention other searching tools when comparing speed, but that's it.
