### ISSUE TITLE
When only one file is returned, it doesn't print the file name

### ISSUE THREAD

**Issue by eksperimental** [ggreer/the_silver_searcher#749]
choose a pattern that will match only one file, and you will not see the name of the file matched.

```sh
$ ag "." *CE
1:The Silver Searcher
2:Copyright 2011-2014 Geoff Greer
3:
```

**Comment by ggreer** [comment]
Sorry, but there's no way to fix this. Ag doesn't see "*CE" in its arguments. It sees whatever the shell expands that to.

If you want file headings all the time, use `ag -H`

**Comment by eksperimental** [comment]
I see. But wouldnt it be better to use the -H option as default, since most of the times is gonna be used, except when there is only one file like in this case. I think it will be more consistent and less prone to surprises like this one

**Comment by ggreer** [comment]
Surprise? Every tool I can think of disables headings when a single file is being seached. That includes grep, ack 1 & 2… even pt.
