### ISSUE TITLE
Add .deb package to releases

### ISSUE THREAD

**Issue by eksperimental** [ggreer/the_silver_searcher#750]
I would love to be able to automatically download from a Continous Integration service like travis,
a deb package, so I could run a quiet a few tests on projects I am working on.
github provides the feature to add additional with files with every release.

**Comment by ggreer** [comment]
Having built .deb files before, there's zero chance I'll do it again. It's a *huge* pain. Sorry.

**Comment by eksperimental** [comment]
:-(
