### ISSUE TITLE
how do i get the result'filename for next command

### ISSUE THREAD

**Issue by hanyimin** [ggreer/the_silver_searcher#754]
i search by ag ，the result like this:
  ➜  a  ag 部件名称
  a.csv
  33:a246,"部件名称",""
 ➜  a

i want to vi the  file a.csv，how can i get the filename quickly in the next commad weather i don't input the filename (if  the file name is very long)

**Comment by netei** [comment]
you could do 

ag "foo"

Get results

    ag "foo" -l  | rvim 

by putting this in your bashrc : 

```
rvim () {
  cat > /tmp/filelist && vim </dev/tty $(cat /tmp/filelist | tr "\n" " ")
}
```

**Comment by hanyimin** [comment]
Thanks netei!

**Comment by netei** [comment]
You might also be interested in https://github.com/edi9999/path-extractor , specifically [issue 2](https://github.com/edi9999/path-extractor/issues/2) which deals with tmux integration
