### ISSUE TITLE
Option to add exceptions to ignored file list?

### ISSUE THREAD

**Issue by kaushalmodi** [ggreer/the_silver_searcher#756]
Is there a way to add exceptions to the list of ignored files/dirs in .agignore.

By default, all files beginning with a dot are ignored. I would like to add exceptions only for few files.

A way to do this might be how .gitignore works; below will ignore all *.log files except abc.log.

``` text
*.log
!abc.log
```

**Comment by ggreer** [comment]
Duplicate of #168.

**Comment by kaushalmodi** [comment]
This is sort of a different issue (not related to .gitignore).
I am requesting the ignore syntax be recognized in `.agignore`.

**Comment by ggreer** [comment]
Ag uses the same parser for all ignore files, so fixing #168 would fix your issue.
