### ISSUE TITLE
How to search for pattern containing both single and double quotes?

### ISSUE THREAD

**Issue by kaushalmodi** [ggreer/the_silver_searcher#759]
I can use `ag '"'` to search for a double quote and `ag "'"` to search for a single quote.

But how do I search for something like `"'abc'"` (including the double and single quotes)? 

Using escapes does not work. I tried both `ag '"\'abc\'"'` and `ag "\"'abc\""`. But neither worked.

**Comment by netei** [comment]
It works fine for me : 

    echo "\"'abc'\"" > foo
    ag "\"'abc'\"" 

        foo       
        1:"'abc'"

**Comment by netei** [comment]
I'm using ag version 0.30

**Comment by kaushalmodi** [comment]
@netei Thanks for confirming.. it is the tcsh shell that's causing me problem (grumble need to use that shell at work grumble). It works fine in bash.

I'll post a solution to this in this thread for other tcsh users.. when I get a solution. But as it is not related to ag, I am closing this issue.

Thanks again.

**Comment by netei** [comment]
You could use the following to properly include `"` : http://stackoverflow.com/questions/382734/escaping-double-quotes-with-tcsh-alias#382770

**Comment by kaushalmodi** [comment]
Thanks! I finally got it resolved. I have been used to using single quotes to wrap my regex; now I guess, I need to start using double quotes in general.

Here is my test script for reference:

```sh
#!/bin/tcsh -f

set dq = '"'; set DQ = $dq # double quote
set sq = "'"; set SQ = $sq # single quote

# '"Hello"'
echo He said "'"'"Hello"'"'" with strange quotation marks. >! temp.foo
echo "Contents of temp.foo:"
cat temp.foo
echo "agging only for Hello .."
\ag Hello temp.foo
echo "agging for Hello with the first double quote .."
\ag ${dq}Hello temp.foo
# Above is the same as \ag "${dq}Hello" temp.foo
\ag "${dq}Hello" temp.foo
echo "agging for Hello with both double quotes .."
\ag "${dq}Hello${dq}" temp.foo
echo "agging for Hello with both double and single quotes .."
\ag "'${dq}Hello${dq}'" temp.foo
# Above is the same as \ag "${sq}${dq}Hello${dq}${sq}" temp.foo
\ag "${sq}${dq}Hello${dq}${sq}" temp.foo
echo ""

# "'Hello'"
echo He said '"'"'Hello'"'"' with strange quotation marks. >! temp.foo
echo "Contents of temp.foo:"
cat temp.foo
echo "agging only for Hello .."
\ag Hello temp.foo
echo "agging for Hello with the first single quote .."
\ag ${sq}Hello temp.foo
# Above is the same as \ag "${sq}Hello" temp.foo
\ag "${sq}Hello" temp.foo
# Above is the same as \ag "'Hello" temp.foo
\ag "'Hello" temp.foo
echo "agging for Hello with both single quotes .."
\ag "'Hello'" temp.foo
# Above is the same as \ag "${sq}Hello${sq}" temp.foo
\ag "${sq}Hello${sq}" temp.foo
echo "agging for Hello with both double and single quotes .."
\ag "${dq}'Hello'${dq}" temp.foo
# Above is the same as \ag "${dq}${sq}Hello${sq}${dq}" temp.foo
\ag "${dq}${sq}Hello${sq}${dq}" temp.foo
```
