### ISSUE TITLE
Find and replace

### ISSUE THREAD

**Issue by Ticki** [ggreer/the_silver_searcher#779]
I use ag a lot, and I'm really happy with it. Often I need to find and replace in a lot of files, this can be done multiple ways. For example:

`ag "sometext" --nogroup | awk '{print substr($1,1,index($1,":")-1);}' | xargs -I {} sed -i .bak -e 's/sometext/anothertext/g' {}`

However, this is quite annoying.

I suggest that a find and replace feature is added using, say a command flag `-r`. I do unfortuately not know a lot of C.

What's your thoughts on this?

**Comment by ggreer** [comment]
Sorry, not happening.

**Comment by Ticki** [comment]
Thanks for your response. I just have a question: do you know a neat ag-like tool that can do this task?

**Comment by ggreer** [comment]
I don't know of anything outside of the basic unix tools. I use awk and sed just like you.

Sorry if I was curt, but ag is read-only. Writing to files would require completely changing the software architecture. Then there would need to be more error handling for issues such as permissions, out of disk space, etc.

**Comment by Ticki** [comment]
No problem. :)

**Comment by neojski** [comment]
I was thinking about replace as well. @Ticki would you mind explaining what your awk does? I did replace with the following:

```bash
ag what -l -0 | xargs -0 sed 's/what/replace-with-this/g'
```
