### ISSUE TITLE
ideas: print match only

### ISSUE THREAD

**Issue by Silex** [ggreer/the_silver_searcher#784]
Hello,

`ag` is an amazing tool, the other day I wished there was a way to have it print only what was matched, for example something like this:

``` shell
$ ag --extract-match 'foo.*bar'

file1
  foo123bar
  foo456bar

file2
  foobar
  foofoobar
```

This is very useful to extract simple informations from log files (emails, phones, whatever)

**Comment by ban-dana** [comment]
ag -o ?

**Comment by Silex** [comment]
@ban-dana: right, I was using an outdated version of `ag` and thus the option wasn't there.

Thanks!
