### ISSUE TITLE
Environment variable for default parameters

### ISSUE THREAD

**Issue by nogweii** [ggreer/the_silver_searcher#79]
I could create an alias, which is what I'll do for now, but it would be pretty awesome if you could pass parameters to ag via an environment variable. sort of like less's LESS or ack's ACK_OPTIONS. I would guess including them in the beginning of the string before passing argv to parse_options would make the most sense.

**Comment by lgarron** [comment]
Anyone looking for the latest status: head straight to #257 (canonical bug number for this issue) and/or #709 (latest pull request).

**Comment by stfl** [comment]
+1
