### ISSUE TITLE
The default git core.excludesfile, ~/.config/git/ignore, is not read

### ISSUE THREAD

**Issue by tomfitzhenry** [ggreer/the_silver_searcher#796]
### Steps to reproduce
```
$ ag --version
ag version 0.31.0

Features:
  +jit +lzma +zlib
$ git --version
git version 2.6.3
$ mkdir foo
$ rm -rf foo
$ mkdir foo
$ echo baz > foo/bar
$ ag baz
foo/bar
1:baz
$ echo 'foo' >> ~/.config/git/ignore
$ ag baz # Unexpected output
foo/bar
1:baz
$ git config --global core.excludesfile ~/.config/git/ignore
$ ag baz # After we explicitly set core.excludesfile, the output is as I expect: empty
```

### Expected
I expect the output of `ag baz` (the invocation annotated with "Unexpected output" above) to be empty.

### Actual
The output is not-empty.

### Why
I expect it to be empty, since ~/.config/git/ignore is the default git exclude file, as described in [gitignore(5)](https://git-scm.com/docs/gitignore):
```
       o   Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files
           generated by the user's editor of choice) generally go into a file specified by
           core.excludesFile in the user's ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore.
           If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.
```

**Comment by ggreer** [comment]
Thanks for the clear and unambiguous bug report. It's a shame git-config can't be made to output the default value for core.excludesfile. If git ever changes those defaults, ag can't easily track it.

**Comment by tomfitzhenry** [comment]
Thanks for the fix! https://stackoverflow.com/questions/33720397/git-config-list-all-variables-and-their-default-values/33720449#33720449 discusses this limitation of git-config. Based on the linked git mailing list thread, it doesn't look like git-config will be able to be coerced into providing the default values, in the short term.
