### ISSUE TITLE
ag never search one of my directory

### ISSUE THREAD

**Issue by YorkZ** [ggreer/the_silver_searcher#804]
I've been using ag for a while, and am very happy with it. However, I just noticed an extremely strange and explainable problem. I was in the directory ~/Documents/myname/some-directory, and typed:

$ ag PATTERN

Ag reported the following:

    333 matches
    20 files contained matches
    208 files searched
    15417674 bytes searched
    0.284677 seconds

The problem is that ag had never searched one of the sub directories for no reason. The entire directory has more than 9000 files, 6 G in total, and I didn't have .agignore file in my directory hierarchy.

I'm using the ag I compiled from the latest git repository, commit 5816116. Please let me know what I can do to help debugging the issue.

Thanks in advance!

**Comment by YorkZ** [comment]
Never mind. I've figured out the reason. It was because that sub directory was in my .gitignore file. The reason why I need this sub directory in my .gitignore is because it has it's own repository, and I didn't want to make it a sub module of it's parent directory repository.

I know I can use the "-U" option, but the problem is I'm not sure whether I can still remember to use "-U" option if I would search this directory again after six months.

Therefore, may I suggest adding the support for `!` syntax to .agignore, to tell ag not to ignore certain files or directories? .gitignore supports the `!` syntax.

I'm sorry for having reported this non-bug!

**Comment by ggreer** [comment]
Sounds like your feature request is the same as #168.
