### ISSUE TITLE
Support Julia's Filetype

### ISSUE THREAD

**Issue by xanderdunn** [ggreer/the_silver_searcher#806]
Add [Julia](https://github.com/JuliaLang/julia)'s .jl filetype to the list of supported FILE TYPES shown in `ag --list-file-types`.

**Comment by stardiviner** [comment]
I think ag should support letting user to define custom file-type in config file.

**Comment by srstevenson** [comment]
I've opened a PR adding Julia to the supported filetypes at https://github.com/ggreer/the_silver_searcher/pull/833.

**Comment by ggreer** [comment]
#833 was merged, so... closing this.
