### ISSUE TITLE
Also consider .bzrignore files

### ISSUE THREAD

**Issue by albertodonato** [ggreer/the_silver_searcher#829]
It'd be great if ag would also ignore files matching patterns in .bzrignore files, as it does for other SCMs.

**Comment by albertodonato** [comment]
#830 has a change for this

**Comment by ggreer** [comment]
Sorry, but I'm against supporting bzr for performance reasons. For more detailed reasoning, see [my comment on this old PR](https://github.com/ggreer/the_silver_searcher/pull/427#issuecomment-183840676).
