### ISSUE TITLE
ag searches through "tags" files by default

### ISSUE THREAD

**Issue by timjstewart** [ggreer/the_silver_searcher#83]
I would love to use ag, but I don't think it should search through my tags file by default.

**Comment by TysonAndre** [comment]
For anyone looking at this issue in the future, if you're trying to exclude the file `tags` (from ctags) from search, but to include `tags/` as a directory in your searches


(does not work, tags/ directory is still ignored)
```
tags
!tags/
```

But this workaround does work - the file is ignored but the files in the directory aren't.

```
[t]ags
!tags/
```
