### ISSUE TITLE
How to update to the latest version?I am using ubuntu 14.04,the ag version is too old

### ISSUE THREAD

**Issue by wsdjeg** [ggreer/the_silver_searcher#832]
![2016-01-30 14 16 13](https://cloud.githubusercontent.com/assets/13142418/12694095/211e6dde-c75c-11e5-9163-fea3fdc19c79.png)

**Comment by wsdjeg** [comment]
can you provide a PPA source like 
https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable
thanks a lot.

**Comment by wsdjeg** [comment]
wow I have find a ppa source,so clossing

**Comment by ggreer** [comment]
Please don't open issues like these. This is tech support, not a bug in ag.

**Comment by wsdjeg** [comment]
yes, sorry for doing like this.
