### ISSUE TITLE
Look at shebang to determine filetype

### ISSUE THREAD

**Issue by jonhiggs** [ggreer/the_silver_searcher#836]
It would be nice if ag checked for a shebang so that `--shell`, `--python`, `--ruby` etc. can match scripts without extensions.

**Comment by ggreer** [comment]
As nice as that would be, it would ruin performance. Right now, matching languages is as easy as looking through the directory entries for the right file extensions. Matching based on the content would require opening each file.

Not to mention, how many different shebangs are there for each language? Shell would have... `#!/bin/sh`, `#!/bin/bash`, `#!/bin/dash`, `#!/bin/zsh`, etc. And for each shell, you'd also have the `#!/usr/bin/env ...` equivalent and the `#!/usr/local/bin/...` equivalent. For python, you also have different binary names (`python`, `python2`, `python3`, `python2.7`, `python3.4`, etc) and virtualenvs (`~/virtualenvs/envname/bin/python`). The number of false positives and false negatives would be huge.
