### ISSUE TITLE
gitignore un-ignores

### ISSUE THREAD

**Issue by sencer** [ggreer/the_silver_searcher#837]
`ag` won't work with simple (or complicated in some sense) `.gitignore` files, like 

````
*
!*.*
````

`git ls-files --others -i --exclude-standard` command is a better way of handling gitignore.

**Comment by Asheboy** [comment]
I'm experiencing this issue too.

**Comment by balaclark** [comment]
I can also confirm that this is a problem.

**Comment by ggreer** [comment]
Duplicate of #168.
