### ISSUE TITLE
The default color scheme is unreadable with a bright background

### ISSUE THREAD

**Issue by cgroth** [ggreer/the_silver_searcher#838]
I believe that the default color scheme should work well also (and especially!) on bright backgrounds.  Yellow should not be used.  How about using red, blue, and bold green?

After all, despite the recent fashion among some terminal users, bright backgrounds are still the default for reading text both on a computer and on paper.  (This is good, since it makes more sense physiologically, but this is not the right place to discuss that.)

**Comment by ggreer** [comment]
Sorry, but the backlash from changing the color scheme would be far greater than the number I get from keeping it the same. The current is a nice Schelling point, as it's also the default color scheme for ack.

If you prefer another scheme, you can alias ag to use options like `--color-line-number`, `--color-match`, and `--color-path`.

**Comment by cgroth** [comment]
Fair enough…  I know that there are options to change the color. 
My remark, however, was about the default color scheme.

I still do not understand how yellow text could be a “natural” 
solution for a console program.  There is a reason why most (all?) 
prominent console tools with a color option avoid yellow (consider 
git, ls, grep, etc.)

**Comment by arpit10i** [comment]
I too find it unreadable. I am not sure in what format the colors need to be supplied.
