### ISSUE TITLE
.gitignore not being respected

### ISSUE THREAD

**Issue by MichaelMackus** [ggreer/the_silver_searcher#844]
For some reason, I've found since updating silver searcher from the Ubuntu repo version (to latest git snapshot) ag doesn't respect gitignore files anymore (only my system $HOME/.agignore seems to be respected). 

Any ideas why this is happening? Even in the README it is advertised it respects gitignore. My ag command is just plain `ag "Query Here"`.

**Comment by mxcoder** [comment]
Having the same problem here:

ag version 0.28.0

Linux ricardo-xxxxxx 3.19.0-51-generic #58-Ubuntu SMP Fri Feb 26 21:22:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

**Comment by dillonhafer** [comment]
I have the same issue. My `.gitignore` looks like:

```
...
log/*.log
```

But `.log` files are still searched. However, change the `.gitignore` to

```
...
log
```

allows `ag` to ignore them.

**Comment by MichaelMackus** [comment]
Seems like this is fixed for me in the latest silversearcher

ag version 0.33.0

**Comment by dillonhafer** [comment]
This is also fixed for me now that I'm on 0.33.0

**Comment by MichaelMackus** [comment]
Going to close as not to pollute issues list.
