### ISSUE TITLE
Duplicate but conflicting definition of enum ag_compression_type

### ISSUE THREAD

**Issue by tautschnig** [ggreer/the_silver_searcher#845]
Hello,

Our compiler goto-cc reported the following conflict:

file src/decompress.c line 220: 
reason for conflict at #this: number of members is different (4/5)
```
enum  { AG_NO_COMPRESSION=0, AG_GZIP=1, AG_COMPRESS=2, AG_ZIP=3 }
enum  { AG_NO_COMPRESSION=0, AG_GZIP=1, AG_COMPRESS=2, AG_ZIP=3, AG_XZ=4 }
error: conflicting function declarations 'is_zipped'
old definition in module 'search' file src/util.h line 78
enum  (const void *, const signed int)
new definition in module `decompress' file src/decompress.c line 220
enum  (const void *buf, const signed int buf_len)
```

This is due to definitions of ag_compression_type both in src/util.h as well as src/decompress.h, where the one in util.h is missing AG_XZ.

Best,
Michael

**Comment by jschpp** [comment]
@tautschnig could you check if my pr solves this?

**Comment by tautschnig** [comment]
@jschpp Thanks a lot for the immediate response, this does indeed fix any warnings previously reported by goto-cc.

Best,
Michael
