### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by jschpp** [ggreer/the_silver_searcher#854]
travis is building inconsistently
Affected:
pr #843 with e4c3a35
pr #852 with 36ad19f

**Comment by jschpp** [comment]
It's notable that e4c3a35 worked partially here: https://travis-ci.org/jschpp/the_silver_searcher/builds/111507171

**Comment by jschpp** [comment]
Well #843 is closed so that's not important anymore.
The build from #852 should be rerun to test it in travis

**Comment by ben-albrecht** [comment]
Hi @jschpp, I am the author of #852 - do I have the ability to rerun the Travis build myself, or should I make some near-empty commit to trigger the auto-build again?

**Comment by jschpp** [comment]
As far as I know you cannot rerun the build yourself except fpr making said near-empty commit

**Comment by jschpp** [comment]
Since both pr build correctly I close this
