### ISSUE TITLE
Delay call to `strlen` in `filename_filter` 

### ISSUE THREAD

**Issue by br0ns** [ggreer/the_silver_searcher#856]
The call to `strlen` in [`ignore.c:344`](https://github.com/ggreer/the_silver_searcher/blob/master/src/ignore.c#L344) could be delayed until the `while` loop on line [395](https://github.com/ggreer/the_silver_searcher/blob/master/src/ignore.c#L395) where the code path should have become "cooler".  I have not benchmarked it though.

**Comment by ggreer** [comment]
Nice catch, though I'm almost certain that the compiler is smart enough to move the `strlen()` down.
