### ISSUE TITLE
Inaccurate results with newlines in --files-without-matching

### ISSUE THREAD

**Issue by da99** [ggreer/the_silver_searcher#859]
I'm getting inaccurate results with the following setup using `ag 0.31`:

```bash
mkdir -p /tmp/ag
echo -e "spec 1\nrandom content"         > /tmp/ag/1.txt
echo -e "\nspec 2"    > /tmp/ag/2.txt
echo -e "spec 3\n"    > /tmp/ag/3.txt
echo -e "\nspec 4\n"  > /tmp/ag/4.txt
ag -l --literal "spec" /tmp/ag
echo "=========================="
ag -L --literal "spec" /tmp/ag
```
The `-L` (`--files-without-match`) here prints  inaccurate matches: `1.txt`, `2.txt`, `3.txt`
It seems to work fine if there is content (even just one newline) before and after the target string (e.g. `4.txt`).

**Comment by jasonkarns** [comment]
dupe of #765?

**Comment by da99** [comment]
It seems like it. Thanks. I'll mark it closed.
