### ISSUE TITLE
searching for something that starts with a dash causes an error

### ISSUE THREAD

**Issue by greg0ire** [ggreer/the_silver_searcher#875]
Version : 0.31.0
Command : `ag -Q '->my function('`
Error message : `ag: invalid option -- '>`

**Comment by gcflymoto** [comment]
Try 
`ag -Q "'->my function('"`
as a workaround

**Comment by greg0ire** [comment]
Thank you, but it does not work for me.

**Comment by srstevenson** [comment]
Ag can't know whether an argument beginning with a dash is an option flag (e.g. `-Q` in your example) or a positional argument that just so happens to start with a dash (`->my function(` in this case). You can tell Ag where the option flags end and positional arguments begin with a double dash (`--`):
```bash
ag -Q -- '->my function('
```
(This works with anything that uses getopt for options parsing, not just Ag.)

**Comment by greg0ire** [comment]
Thanks, it works! So this is more a limitation of my shell I guess (in which case this should be closed).
