### ISSUE TITLE
Concrete example of ack not finding a pattern it should.

### ISSUE THREAD

**Issue by kozikow** [ggreer/the_silver_searcher#902]
Example of ag not working on the open source repository https://github.com/twosigma/beaker-notebook.

ag "JerseyLogger" finds a pattern when launched from beaker-notebook/core/src, but not from beaker-notebook/core. "grep -R" or "ack" find a pattern from both directories.

**Comment by ggreer** [comment]
That's because ag is obeying the `.gitignore` in `beaker-notebook/core`.
