### ISSUE TITLE
With * in gitignore, ag will get wrong result

### ISSUE THREAD

**Issue by gngshn** [ggreer/the_silver_searcher#915]
Because there is some other git repo in one git repo, these is a pattern \* in the .gitignore file in deeply directories in our project. This lead ag don't search files in these directories.

```
|-a gitrepo dir
|----file1
|----file2
|----dir1
|----.git dir
|----.gitignore
|----deep dir
|----|----.gitignore with * pattern
|----|----gitrepo1 dir
|----|----gitrepo2 dir
|----|----....
```

Ag will ignore all gitrepo1/2/... dirs in deep dir
So, can ag ignore the '*' in .gitignore?
Ack-grep have ignored the \* in gitignore.

**Comment by CleanCut** [comment]
I think I have a related issue.

I have a repository whose `.gitignore` looks like this.

```
*
!*/
!*.c
!*.cc
(etc.)
```

But ag ignores all files, even though the `.c` and `.cc` files were explicitly excluded from being ignored.

So I run `ag -u` and it takes forever, because it is searching through ~6GB of binary files produced by the project (which is why .gitignore is set up like it is).

Someone please let me know if I should make a separate issue for this.

**Comment by msmith491** [comment]
I've also hit this issue.  Here is my .gitignore file:
```
*.swp
*
!/**/
!*.*
nimcache/
```
I use `ag` as the file aggregator for my Vim fuzzy searcher with `ag -g ""`, and with this .gitignore file I get nothing returned.

**Comment by rudle** [comment]
https://github.com/Homebrew/brew/blob/master/.gitignore is an example of a gitignore file that will confuse The Silver Searcher

**Comment by msmith491** [comment]
I've narrowed down to problem to here: https://github.com/ggreer/the_silver_searcher/blob/master/src/ignore.c#L333 .  It appears that `fnmatch` matches everything if a `*` character is provided and ag doesn't respect `.gitignore` includes after this.  Unfortunately this is a hot loop and my C-fu is weak enough that I'm not sure what I can change without severely affecting `ag`'s performance.

**Comment by alecdwm** [comment]
@msmith491 With your changes, given the following fs structure:
```
.
./file
./dir
./dir/file
./dir/dir2
./dir/dir2/file
./.gitignore
./.git
```
With the following .gitignore:
```
*
!file
!dir
!dir/*
```
Git will see:
```
	new file:   dir/dir2/file
	new file:   dir/file
	new file:   file
```
But ag will only see:
```
dir/file
file
```

My C-fu is even weaker, but I thought it might be helpful to provide this feedback.

**Comment by benwaffle** [comment]
It works for me with `*` but not `/*` in a subdirectory

**Comment by LukasMac** [comment]
I can confirm that it does not work with `dir/*.map.js`

**Comment by ggreer** [comment]
I've added support for ignore files containing a "*" rule and excludes like "!*.js" in #1101. The next release of ag will have this feature.

**Comment by CleanCut** [comment]
That's great!  Thank you!

**Comment by piotryordanov** [comment]
@ggreer When is the next release planned?

**Comment by maneyko** [comment]
I am having this issue with ag (version 2.2.0, +jit, +lzma, +zlib). I have `log/*.log` in my .gitignore for my project, and it is still searching in files that match, such as `log/development.log`. When I add `log/*` to my ~/.gitignore_global (I don't want to change my project's gitignore), then it ignores files in `log/`.

**Comment by rileyrg** [comment]
2020 and... with something like
*
!/include-me
!/inclde-me/*

it doesn't work. It wont search the include me directory.

**Comment by MikyStar** [comment]
With the version available from Homebrew, ag doesn't understand this type of folder notation either

```
**/folder
```

**Comment by nwg** [comment]
Just ran into this issue. My gitignore uses exclusion followed by inclusion like in the earlier comments:

    *
    !.gitignore
    !*.org
    !*.org_archive
    !*/
