### ISSUE TITLE
rpm link in RHEL7+ installation instructions return 404

### ISSUE THREAD

**Issue by davidcpell** [ggreer/the_silver_searcher#928]
I'm working on installing `ag` on a Centos 7.2 machine, so I'm following the instructions for RHEL7+. When I try to run the first step:

`rpm -Uvh http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm`

I get a 404 error (same thing if I just paste the URL into a web browser).

Any recommendations?

**Comment by jschpp** [comment]
try this instead `yum install epel-release.noarch`
then `yum install the_silver_searcher`

**Comment by davidcpell** [comment]
Thanks, @jschpp. That worked! I've opened #929 to update the `README` if you don't mind giving that a look.

**Comment by ggreer** [comment]
Fixed by #929.
