### ISSUE TITLE
Tag Library Descriptor files support

### ISSUE THREAD

**Issue by caneta** [ggreer/the_silver_searcher#930]
I see from `ag --list-file-types` that the `.tld` extension is missing.

[Tag Library Descriptor files](http://www.careerride.com/JSP-what-is-Tag-library-descriptor-%28TLD%29.aspx) are basically XML files so is that possible to add their extension to the `--xml` flag?

Thank you.

**Comment by ggreer** [comment]
Fixed in #933.
