### ISSUE TITLE
How to search a literal string starting with a dash?

### ISSUE THREAD

**Issue by 0x1997** [ggreer/the_silver_searcher#941]
I'm trying to search for usage of a struct member but the dash character is always interpreted by `getopt` as start of an option. 

```shell
>> ag -Q '->poll'
ag: invalid option -- '>'
```

**Comment by jschpp** [comment]
try this: `ag -Q -- '->poll'`

**Comment by 0x1997** [comment]
@jschpp thanks!

**Comment by jschpp** [comment]
No problem. By the way this works with pretty much every unix command
