### ISSUE TITLE
Include .tpp as a C++ extension

### ISSUE THREAD

**Issue by slizzered** [ggreer/the_silver_searcher#946]
Some C++ projects ([example](https://github.com/ComputationalRadiationPhysics/picongpu)) with very template-heavy code bases split their headers into "regular" `.hpp` files and `.tpp` files that are included like headers but contain the template implementations.

I suggest adding `.tpp` as one of the extensions that is seached when using the `--cpp` switch.

**Comment by jschpp** [comment]
#947 Should implement this
