### ISSUE TITLE
No way to issue a `start of string` pattern for ag

### ISSUE THREAD

**Issue by ninrod** [ggreer/the_silver_searcher#952]
I'm trying to find all file whose filename starts with 'foo' using pcre syntax:

```sh
$ ag -g '\^foo'
$ ag -g '^foo'
$ ag -g '\Afoo'
$ 
```

This does not work, but it should as it is following PCRE standard syntax. I think it's a bug. 

so question [link](http://unix.stackexchange.com/q/302876/155613)

**Comment by bmalehorn** [comment]
`ag` will search the whole pathname, so the search query `^/foo` won't match `/home/ninrod/foo`. Instead, you'll have to change the search a bit:

    ag -g '/foo[^/]*$'

**Comment by ninrod** [comment]
Oh, ok, totally missed that.  Thank you @bmalehorn.
