### ISSUE TITLE
could you please add support for ignore pattern like "*.pb.h" ;-)

### ISSUE THREAD

**Issue by DavidFeng** [ggreer/the_silver_searcher#958]
it is useful sometimes like google protocol buffer generate files with name end with *.pb.cc  and *.pb.h

ps: git can process this in .gitignore

**Comment by khingblue** [comment]
Try `--ignore=*.pb.h`

**Comment by DavidFeng** [comment]
thanks for your tips and your great work

ps: I have found the source of this feature, maybe some day I will send you a pull request when I have time.
