### ISSUE TITLE
Support grep like multi-files output result.

### ISSUE THREAD

**Issue by zw963** [ggreer/the_silver_searcher#970]
When I use grep, I can get all matched result like this:

```sh
./app/controllers/api/v1/my/follow_search_keywords_controller.rb:32:    path: '/v1/follow_search_keywords',
./app/controllers/api/v1/my/follow_search_keywords_controller.rb:43:    "following_search_keywords": [
./app/controllers/api/v1/my/follow_search_keywords_controller.rb:63:    'api/v1/follow_search_keyword#create',
```

I can convenient copy the first part, in this case, e.g.

``./app/controllers/api/v1/my/follow_search_keywords_controller.rb:32:``

And, use my editor to open this line as file name.

e.g.

```sh
$: e  ./app/controllers/api/v1/my/follow_search_keywords_controller.rb:32:
```
Basically, I do some split between delimiter `:`
so I can got correct file name and line number.

It so comfortable for me.

Because this reason, I try to switch to ag many times ... but  give up finally.

**Comment by padawin** [comment]
Hello,

If you provide the option --vimgrep, it should make the trick:
```
> ag test2
foo
2:test2
> ag test2 --vimgrep
foo:2:1:test2
```

**Comment by zw963** [comment]
Yes, it worked, Thanks.

though, if add with --color-??? arguments, will fallback to default behavior.

I can use grep to work around this.
