### ISSUE TITLE
Files with non-english characters are trait as binary files

### ISSUE THREAD

**Issue by vsushkov** [ggreer/the_silver_searcher#98]
Files with non-english characters are trait as binary files. Test data set:

```
test
тест
```

Put this two lines in a file and search for "test".

**Comment by sergeevabc** [comment]
Windows 7, ag 2.2.0 (downloaded [here][1])
File hello.txt inside folder Test.
Contents of hello.txt is 'Привет, мир!'
```ag мир``` -> nothing :-1: 
```rg мир``` -> hello.txt 1:Привет, _мир_! :+1:  

[1]: https://github.com/k-takata/the_silver_searcher-win32/releases/tag/2020-02-25/2.2.0-24-gb93c271

**Comment by PackmanDude** [comment]
just don't use ruzzian.
