### ISSUE TITLE
Feature request: Support both --no<option> and --no-<option>

### ISSUE THREAD

**Issue by okdana** [ggreer/the_silver_searcher#980]
A while ago you decided to standardise the option negation prefix to `no` without a hyphen — so `--nogroup` as opposed to `--no-group`. Whilst standardising them is great, i find that, even with using `ag` almost every day, i *still* get confused about it.

Much of that seems to be habit instilled by other software i've used. I checked the man pages of my top 20 most used commands, and almost every single one that had a 'no'-style option used `no-` with the hyphen — `git`, GNU `grep`, `rsync`, `psql`, `php`, `composer`, `brew`, GNU `make`, &c. The only one i could find that used `no` without the hyphen was `vim`. And, personally, i think it only *makes sense* to use the hyphen when you're using it as a word separator in options elsewhere (as `ag` does with `--case-sensitive`, `--max-count`, &c.).

With that said, the obvious solution to please everyone and maintain backwards compatibility would be to just support both forms. They don't both have to be documented or shown in the usage help, just silently accept them and everybody's cool.

Would that be OK with you? If so, i can put together a PR. Let me know how you feel. Thanks again!

**Comment by ggreer** [comment]
I chose no hyphen because that's what ack v1 did. Now that ack v2 is out and its features have diverged from ag, I guess it doesn't make much sense. You also make some good points about other tools and how every other word is separated by a dash.

If you want to make a PR, go for it.

**Comment by okdana** [comment]
Cool! Closing in favour of PR #984.
