### ISSUE TITLE
option to specify search pattern explicitly

### ISSUE THREAD

**Issue by theimpostor** [ggreer/the_silver_searcher#982]
I don't see an obvious way to search for a pattern that looks like an option. E.g., say I wanted to search for the string "----------------------": 

`$ag '----------------------' -Q
ag: unknown option -- --------------------`

Ack has this implemented as the '--match' option.

**Comment by jschpp** [comment]
See #941 
Specific [my comment](https://github.com/ggreer/the_silver_searcher/issues/941#issuecomment-232895024)

**Comment by theimpostor** [comment]
Thanks, I forgot about double dash. Seeing as this has been raised as an issue multiple times now, should there perhaps be a note or example in the man page? It is mentioned in the man pages of 'rm' and 'find' on my system:

> To remove a file whose name starts with a '-', for example '-foo', use one of these commands:
> 
>               rm -- -foo

And from `man find`:

> A double dash -- can also  be  used to signal that any remaining arguments are not options

**Comment by jschpp** [comment]
I think that a note in the manpage would be helpful.

**Comment by okdana** [comment]
I've seen this come up a lot on here too. Submitted PR #985 to add an example to the manual.

**Comment by ggreer** [comment]
Thanks for the PR, @okdana. I'm closing this now that `--` is documented.
