### ISSUE TITLE
Add a -o option (showing only matching parts)

### ISSUE THREAD

**Issue by richarno** [ggreer/the_silver_searcher#990]
ag is extremely useful to me, I use it tens of times a day.
However I sometimes resort to "`find dir -type f -exec grep -o mypattern {} \;`" _just_ because of grep's -o option.
I would greatly appreciate if you can add it to your ag tool.

Thanks a lots for your efforts.
Bruno.

**Comment by okdana** [comment]
`ag` has an `-o` option since [December 2014](https://github.com/ggreer/the_silver_searcher/commit/6cf8bf847b263e378f17594ab965a3b1a34d24b1), version 0.28.0 i think

```
dreameater:~ % ag --help | ag -w -- o
  -o --only-matching      Prints only the matching part of the lines
```

**Comment by richarno** [comment]
OK sorry for the annoyance.
Unfortunately on Debian (which I use) we still have version 0.26.0. This explains why the -o is not yet present.
